from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from enum import Enum
from typing import Protocol

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.inventory_count_event import (
    InventoryCountEvent,
)
from app.services.inventory_count_history_service import (
    InventoryCountTarget,
)


class InventoryCountPhysicalDirection(str, Enum):
    INCREASE = "increase"
    DECREASE = "decrease"


@dataclass(frozen=True)
class InventoryCountPhysicalResult:
    """
    Physical ADJUSTMENT provenance for a non-zero variance.

    Zero variance returns None from create_variance_adjustment().
    """

    document_id: int
    document_line_id: int
    product_id: int
    warehouse_id: int
    direction: InventoryCountPhysicalDirection
    quantity: Decimal


class InventoryCountPhysicalFactory(Protocol):
    async def create_variance_adjustment(
        self,
        db: AsyncSession,
        *,
        target: InventoryCountTarget,
        created_by: int,
    ) -> InventoryCountPhysicalResult | None:
        """
        Create/post ADJUSTMENT only when variance != 0.

        Must not commit or rollback.
        """
        ...

    async def reverse_variance_adjustment(
        self,
        db: AsyncSession,
        *,
        original_event: InventoryCountEvent,
        reversal_date,
        created_by: int,
    ) -> None:
        """
        Reverse physical variance generated by original count.

        If original variance == 0, implementation may be a no-op.

        Must not commit or rollback.
        """
        ...
