"""add persistent tax calculations

Revision ID: 041c0168af79
Revises: 9098606a8126
Create Date: 2026-08-29 18:31:41.278696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041c0168af79'
down_revision: Union[str, Sequence[str], None] = '9098606a8126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade_document_id', sa.Integer(), nullable=False),
    sa.Column('trade_document_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.Enum('vat', name='tax_type_enum'), nullable=False),
    sa.Column('direction', sa.Enum('input', 'output', name='tax_direction_enum'), nullable=False),
    sa.Column('tax_rate_code', sa.String(length=50), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('treatment', sa.Enum('taxable', 'zero_rated', 'exempt', 'out_of_scope', name='tax_treatment_enum'), nullable=False),
    sa.Column('recognition_method', sa.Enum('first_event', 'cash_method', 'manual', name='tax_recognition_method_enum'), nullable=False),
    sa.Column('taxable_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(treatment = 'taxable' AND tax_rate > 0) OR (treatment IN ('zero_rated', 'exempt', 'out_of_scope') AND tax_rate = 0)", name='ck_tax_calculations_treatment_rate_consistency'),
    sa.CheckConstraint("direction IN ('input', 'output')", name='ck_tax_calculations_direction'),
    sa.CheckConstraint("recognition_method IN ('first_event', 'cash_method', 'manual')", name='ck_tax_calculations_recognition_method'),
    sa.CheckConstraint("tax_type IN ('vat')", name='ck_tax_calculations_tax_type'),
    sa.CheckConstraint("treatment IN ('taxable', 'zero_rated', 'exempt', 'out_of_scope')", name='ck_tax_calculations_treatment'),
    sa.CheckConstraint("treatment NOT IN ('zero_rated', 'exempt', 'out_of_scope') OR tax_amount = 0", name='ck_tax_calculations_zero_tax_treatment_amount'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_tax_calculations_currency_code_length'),
    sa.CheckConstraint('char_length(trim(tax_rate_code)) > 0', name='ck_tax_calculations_tax_rate_code_nonempty'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_tax_calculations_tax_amount_nonnegative'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 1', name='ck_tax_calculations_tax_rate_range'),
    sa.CheckConstraint('taxable_base >= 0', name='ck_tax_calculations_taxable_base_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'trade_document_id', 'trade_document_line_id', 'product_id'], ['trade_document_lines.company_id', 'trade_document_lines.trade_document_id', 'trade_document_lines.id', 'trade_document_lines.product_id'], name='fk_tax_calculations_company_trade_document_line_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_tax_calculations_company_id_id'),
    sa.UniqueConstraint('company_id', 'trade_document_id', 'trade_document_line_id', 'tax_type', name='uq_tax_calculations_source_line_tax_type')
    )
    op.create_index(op.f('ix_tax_calculations_calculation_date'), 'tax_calculations', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_tax_calculations_company_id'), 'tax_calculations', ['company_id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_product_id'), 'tax_calculations', ['product_id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_trade_document_id'), 'tax_calculations', ['trade_document_id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_trade_document_line_id'), 'tax_calculations', ['trade_document_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_calculations_trade_document_line_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_trade_document_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_product_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_company_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_calculation_date'), table_name='tax_calculations')
    op.drop_table('tax_calculations')

    sa.Enum(
        "first_event",
        "cash_method",
        "manual",
        name="tax_recognition_method_enum",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        "taxable",
        "zero_rated",
        "exempt",
        "out_of_scope",
        name="tax_treatment_enum",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        "input",
        "output",
        name="tax_direction_enum",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        "vat",
        name="tax_type_enum",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
