"""add payroll journal source exclusivity

Revision ID: 080a2cca7057
Revises: 2895fbd3b558
Create Date: 2026-10-03 13:20:03.482398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080a2cca7057'
down_revision: Union[str, Sequence[str], None] = '2895fbd3b558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_je_payroll_calculation_exclusive', 'journal_entries', 'payroll_calculation_id IS NULL OR num_nonnulls(customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_je_payroll_calculation_exclusive', 'journal_entries', type_='check')
    # ### end Alembic commands ###
