"""add fixed asset foundation

Revision ID: 0a3d68a376e7
Revises: d1552cd41bf1
Create Date: 2026-09-25 15:24:25.703581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3d68a376e7'
down_revision: Union[str, Sequence[str], None] = 'd1552cd41bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('asset_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('in_service_date', sa.Date(), nullable=True),
    sa.Column('original_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.Enum('straight_line', 'diminishing_balance', 'double_diminishing_balance', 'cumulative', 'production', name='fixed_asset_depreciation_method', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready_for_commissioning', 'in_service', 'suspended', 'disposed', name='fixed_asset_status', native_enum=False), nullable=False),
    sa.Column('asset_account_id', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation_account_id', sa.Integer(), nullable=False),
    sa.Column('depreciation_expense_account_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('in_service_date IS NULL OR in_service_date >= acquisition_date', name='ck_fixed_assets_in_service_not_before_acquisition'),
    sa.CheckConstraint('original_cost >= 0', name='ck_fixed_assets_original_cost_nonnegative'),
    sa.CheckConstraint('salvage_value <= original_cost', name='ck_fixed_assets_salvage_not_above_cost'),
    sa.CheckConstraint('salvage_value >= 0', name='ck_fixed_assets_salvage_value_nonnegative'),
    sa.CheckConstraint('useful_life_months > 0', name='ck_fixed_assets_useful_life_positive'),
    sa.ForeignKeyConstraint(['company_id', 'accumulated_depreciation_account_id'], ['accounts.company_id', 'accounts.id'], name='fk_fixed_assets_company_accum_depr_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'asset_account_id'], ['accounts.company_id', 'accounts.id'], name='fk_fixed_assets_company_asset_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'depreciation_expense_account_id'], ['accounts.company_id', 'accounts.id'], name='fk_fixed_assets_company_depr_expense_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'asset_number', name='uq_fixed_assets_company_asset_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_fixed_assets_company_id_id')
    )
    op.create_index('ix_fixed_assets_accumulated_depreciation_account_id', 'fixed_assets', ['accumulated_depreciation_account_id'], unique=False)
    op.create_index('ix_fixed_assets_asset_account_id', 'fixed_assets', ['asset_account_id'], unique=False)
    op.create_index('ix_fixed_assets_company_status', 'fixed_assets', ['company_id', 'status'], unique=False)
    op.create_index('ix_fixed_assets_depreciation_expense_account_id', 'fixed_assets', ['depreciation_expense_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fixed_assets_depreciation_expense_account_id', table_name='fixed_assets')
    op.drop_index('ix_fixed_assets_company_status', table_name='fixed_assets')
    op.drop_index('ix_fixed_assets_asset_account_id', table_name='fixed_assets')
    op.drop_index('ix_fixed_assets_accumulated_depreciation_account_id', table_name='fixed_assets')
    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
