"""create counterparties

Revision ID: 0dbf6ecffcd6
Revises: b8d4e2a1c6f0
Create Date: 2026-08-24 19:43:40.129393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbf6ecffcd6'
down_revision: Union[str, Sequence[str], None] = 'b8d4e2a1c6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_type', sa.Enum('customer', 'supplier', 'both', name='counterparty_type_enum', native_enum=False), server_default='both', nullable=False),
    sa.Column('edrpou', sa.String(length=8), nullable=True),
    sa.Column('tax_number', sa.String(length=20), nullable=True),
    sa.Column('vat_status', sa.Enum('unknown', 'non_vat_payer', 'vat_payer', name='counterparty_vat_status_enum', native_enum=False), server_default='unknown', nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('default_currency_code', sa.String(length=3), server_default='UAH', nullable=False),
    sa.Column('payment_term_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("counterparty_type IN ('customer', 'supplier', 'both')", name='counterparty_type_enum'),
    sa.CheckConstraint("vat_status IN ('unknown', 'non_vat_payer', 'vat_payer')", name='counterparty_vat_status_enum'),
    sa.CheckConstraint('char_length(default_currency_code) = 3', name='ck_counterparty_currency_code_length'),
    sa.CheckConstraint('credit_limit >= 0', name='ck_counterparty_credit_limit_nonnegative'),
    sa.CheckConstraint('payment_term_days >= 0', name='ck_counterparty_payment_term_days_nonnegative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'edrpou', name='uq_counterparty_company_edrpou'),
    sa.UniqueConstraint('company_id', 'tax_number', name='uq_counterparty_company_tax_number'),
    sa.UniqueConstraint('company_id', 'vat_number', name='uq_counterparty_company_vat_number')
    )
    op.create_index(op.f('ix_counterparties_company_id'), 'counterparties', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_company_id'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
