"""create contracts

Revision ID: 13783d5f542a
Revises: 0dbf6ecffcd6
Create Date: 2026-08-25 14:33:46.385251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13783d5f542a'
down_revision: Union[str, Sequence[str], None] = '0dbf6ecffcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_counterparties_company_id_id', 'counterparties', ['company_id', 'id'])
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.Enum('sales', 'purchase', 'mixed', name='contract_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='contract_status_enum', native_enum=False), server_default='draft', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), server_default='UAH', nullable=False),
    sa.Column('payment_term_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contract_type IN ('sales', 'purchase', 'mixed')", name='contract_type_enum'),
    sa.CheckConstraint("status IN ('draft', 'active', 'closed')", name='contract_status_enum'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_contract_currency_code_length'),
    sa.CheckConstraint('credit_limit >= 0', name='ck_contract_credit_limit_nonnegative'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_contract_date_range'),
    sa.CheckConstraint('payment_term_days >= 0', name='ck_contract_payment_term_days_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'counterparty_id'], ['counterparties.company_id', 'counterparties.id'], name='fk_contracts_company_counterparty', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'counterparty_id', 'number', name='uq_contract_company_counterparty_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_contracts_company_id_id')
    )
    op.create_index(op.f('ix_contracts_company_id'), 'contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contracts_counterparty_id'), 'contracts', ['counterparty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_counterparty_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_company_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_constraint('uq_counterparties_company_id_id', 'counterparties', type_='unique')
    # ### end Alembic commands ###
