"""payroll opening inputs

Revision ID: 13d4a7b8c007
Revises: 13d4a7b8c006
Create Date: 2026-10-04 17:28:34.689073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d4a7b8c007'
down_revision: Union[str, Sequence[str], None] = '13d4a7b8c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_earnings_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('cutover_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vacation_earnings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sick_earnings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vacation_days', sa.Integer(), nullable=False),
    sa.Column('sick_days', sa.Integer(), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('extract(day from month) = 1 AND month < cutover_date', name='ck_payroll_earnings_history_month'),
    sa.CheckConstraint('gross_amount >= 0 AND vacation_earnings >= 0 AND sick_earnings >= 0', name='ck_payroll_earnings_history_amounts'),
    sa.CheckConstraint('vacation_days BETWEEN 0 AND 31 AND sick_days BETWEEN 0 AND 31', name='ck_payroll_earnings_history_days'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_earnings_history_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employment_contract_id', 'month', name='uq_payroll_earnings_history_month'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_earnings_history_company_id')
    )
    op.create_table('payroll_leave_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('working_year_start', sa.Date(), nullable=False),
    sa.Column('working_year_end', sa.Date(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('remaining_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("leave_type IN ('annual','additional','social') AND remaining_days >= 0", name='ck_payroll_leave_opening_days'),
    sa.CheckConstraint('working_year_end >= working_year_start AND as_of >= working_year_start', name='ck_payroll_leave_opening_dates'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_leave_opening_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employment_contract_id', 'leave_type', 'working_year_start', name='uq_payroll_leave_opening_year'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_leave_opening_company_id')
    )
    op.create_table('payroll_opening_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=200), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'opening_balance_id'], ['opening_balances.company_id', 'opening_balances.id'], name='fk_payroll_opening_package_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_opening_package_company_id'),
    sa.UniqueConstraint('company_id', 'opening_balance_id', name='uq_payroll_opening_package_source'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_payroll_opening_package_request')
    )
    op.create_table('payroll_opening_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.CheckConstraint("net_amount <> 0 AND currency_code = 'UAH'", name='ck_payroll_opening_debt_amount'),
    sa.ForeignKeyConstraint(['company_id', 'employee_id'], ['employees.company_id', 'employees.id'], name='fk_payroll_opening_debt_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'package_id'], ['payroll_opening_packages.company_id', 'payroll_opening_packages.id'], name='fk_payroll_opening_debt_package', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_id', name='uq_payroll_opening_debt_employee'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_opening_debt_company_id')
    )
    op.execute("""CREATE FUNCTION reject_payroll_opening_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Payroll opening inputs are immutable; append a correction'; END; $$""")
    for table in ('payroll_earnings_history','payroll_leave_openings','payroll_opening_packages','payroll_opening_debts'):
        op.execute(f'CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_payroll_opening_mutation()')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ('payroll_earnings_history','payroll_leave_openings','payroll_opening_packages','payroll_opening_debts'):
        op.execute(f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM {table}) THEN RAISE EXCEPTION 'Payroll opening history must be preserved'; END IF; END $$")
    op.drop_table('payroll_opening_debts')
    op.drop_table('payroll_opening_packages')
    op.drop_table('payroll_leave_openings')
    op.drop_table('payroll_earnings_history')
    op.execute('DROP FUNCTION reject_payroll_opening_mutation()')
    # ### end Alembic commands ###
