"""payroll earning supplements

Revision ID: 13d4a7b8c008
Revises: 13d4a7b8c007
Create Date: 2026-10-04 17:46:23.917607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d4a7b8c008'
down_revision: Union[str, Sequence[str], None] = '13d4a7b8c007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_input_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('request_key', sa.String(length=200), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('bonus','holiday_bonus','hardship','night','overtime','rest_day','regular_extra')", name='ck_payroll_supplement_kind'),
    sa.CheckConstraint('(cancelled_at IS NULL) = (cancelled_by IS NULL)', name='ck_payroll_supplement_cancel'),
    sa.CheckConstraint('minutes >= 0 AND coefficient >= 0 AND amount >= 0', name='ck_payroll_supplement_values'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_input_id'], ['payroll_inputs.company_id', 'payroll_inputs.id'], name='fk_payroll_supplement_input', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_supplement_company_id'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_payroll_supplement_request')
    )
    op.add_column('payroll_calculation_lines', sa.Column('source_supplement_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_payroll_calculation_line_supplement', 'payroll_calculation_lines', 'payroll_supplements', ['company_id', 'source_supplement_id'], ['company_id', 'id'], ondelete='RESTRICT')
    _replace_line_checks(with_supplements=True)
    op.create_check_constraint('ck_payroll_calculation_line_supplement_source',
        'payroll_calculation_lines',
        "(line_type = 'supplement') = (source_supplement_id IS NOT NULL)")


def _replace_line_checks(*, with_supplements):
    kinds = "('salary','supplement')" if with_supplements else "('salary')"
    checks = {
        'rate_nonnegative': f"(line_type IN {kinds} AND rate >= 0) OR line_type = 'manual_adjustment'",
        'amount_by_type': f"(line_type IN {kinds} AND amount >= 0) OR line_type = 'manual_adjustment'",
        'type': "line_type IN ('salary','manual_adjustment','supplement')" if with_supplements else "line_type IN ('salary','manual_adjustment')",
    }
    for suffix, expression in checks.items():
        name = 'ck_payroll_calculation_lines_' + suffix
        op.drop_constraint(name, 'payroll_calculation_lines', type_='check')
        op.create_check_constraint(name, 'payroll_calculation_lines', expression)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM payroll_supplements)
           OR EXISTS (SELECT 1 FROM payroll_calculation_lines WHERE line_type='supplement') THEN
            RAISE EXCEPTION 'Cannot downgrade payroll supplements with history';
        END IF;
    END $$""")
    op.drop_constraint('ck_payroll_calculation_line_supplement_source', 'payroll_calculation_lines', type_='check')
    _replace_line_checks(with_supplements=False)
    op.drop_constraint('fk_payroll_calculation_line_supplement', 'payroll_calculation_lines', type_='foreignkey')
    op.drop_column('payroll_calculation_lines', 'source_supplement_id')
    op.drop_table('payroll_supplements')
    # ### end Alembic commands ###
