"""add tax credit evidence

Revision ID: 147c44d3f4f1
Revises: 009c26582643
Create Date: 2026-09-02 17:42:59.900720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147c44d3f4f1'
down_revision: Union[str, Sequence[str], None] = '009c26582643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_credit_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tax_calculation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('evidence_number', sa.String(length=120), nullable=False),
    sa.Column('evidence_date', sa.Date(), nullable=False),
    sa.Column('credit_available_date', sa.Date(), nullable=False),
    sa.Column('evidenced_taxable_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('evidenced_tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("evidence_type IN ('registered_tax_invoice', 'registered_adjustment', 'customs_declaration', 'article_201_11_document', 'nonresident_self_invoice')", name='ck_tax_credit_evidence_evidence_type'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_tax_credit_evidence_currency_code_length'),
    sa.CheckConstraint('char_length(trim(evidence_number)) > 0', name='ck_tax_credit_evidence_evidence_number_nonempty'),
    sa.CheckConstraint('evidenced_tax_amount > 0', name='ck_tax_credit_evidence_tax_amount_positive'),
    sa.CheckConstraint('evidenced_taxable_base >= 0', name='ck_tax_credit_evidence_taxable_base_nonnegative'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_of_id <> id', name='ck_tax_credit_evidence_not_self_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id', 'tax_calculation_id'], ['tax_credit_evidence.company_id', 'tax_credit_evidence.id', 'tax_credit_evidence.tax_calculation_id'], name='fk_tax_credit_evidence_company_reversal_tax_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'tax_calculation_id'], ['tax_calculations.company_id', 'tax_calculations.id'], name='fk_tax_credit_evidence_company_tax_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', 'tax_calculation_id', name='uq_tax_credit_evidence_company_id_id_tax_calculation'),
    sa.UniqueConstraint('company_id', 'id', name='uq_tax_credit_evidence_company_id_id'),
    sa.UniqueConstraint('reversal_of_id', name='uq_tax_credit_evidence_reversal_of')
    )
    op.create_index(op.f('ix_tax_credit_evidence_company_id'), 'tax_credit_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_tax_credit_evidence_credit_available_date'), 'tax_credit_evidence', ['credit_available_date'], unique=False)
    op.create_index(op.f('ix_tax_credit_evidence_evidence_date'), 'tax_credit_evidence', ['evidence_date'], unique=False)
    op.create_index(op.f('ix_tax_credit_evidence_reversal_of_id'), 'tax_credit_evidence', ['reversal_of_id'], unique=False)
    op.create_index('ix_tax_credit_evidence_source_original', 'tax_credit_evidence', ['company_id', 'tax_calculation_id', 'evidence_type', 'evidence_number', 'id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.create_index(op.f('ix_tax_credit_evidence_tax_calculation_id'), 'tax_credit_evidence', ['tax_calculation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_credit_evidence_tax_calculation_id'), table_name='tax_credit_evidence')
    op.drop_index('ix_tax_credit_evidence_source_original', table_name='tax_credit_evidence', postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.drop_index(op.f('ix_tax_credit_evidence_reversal_of_id'), table_name='tax_credit_evidence')
    op.drop_index(op.f('ix_tax_credit_evidence_evidence_date'), table_name='tax_credit_evidence')
    op.drop_index(op.f('ix_tax_credit_evidence_credit_available_date'), table_name='tax_credit_evidence')
    op.drop_index(op.f('ix_tax_credit_evidence_company_id'), table_name='tax_credit_evidence')
    op.drop_table('tax_credit_evidence')
    # ### end Alembic commands ###
