"""add persistent trade fulfillment

Revision ID: 152e2100aa38
Revises: aff9cb99d26a
Create Date: 2026-08-27 18:09:48.431602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152e2100aa38'
down_revision: Union[str, Sequence[str], None] = 'aff9cb99d26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_documents_company_id_id_document_type', 'documents', ['company_id', 'id', 'document_type'])
    op.create_unique_constraint('uq_document_lines_fulfillment_target', 'document_lines', ['document_id', 'id', 'product_id', 'warehouse_id'])
    op.create_table('trade_fulfillments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade_document_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_document_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_document_type', sa.String(length=20), server_default='issue', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("warehouse_document_type = 'issue'", name='ck_trade_fulfillment_warehouse_document_issue'),
    sa.ForeignKeyConstraint(['company_id', 'trade_document_id'], ['trade_documents.company_id', 'trade_documents.id'], name='fk_trade_fulfillments_company_trade_document', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'warehouse_document_id', 'warehouse_document_type'], ['documents.company_id', 'documents.id', 'documents.document_type'], name='fk_trade_fulfillments_company_warehouse_document', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', 'trade_document_id', 'warehouse_document_id', name='uq_trade_fulfillments_line_source'),
    sa.UniqueConstraint('company_id', 'warehouse_document_id', name='uq_trade_fulfillments_company_warehouse_document')
    )
    op.create_index(op.f('ix_trade_fulfillments_company_id'), 'trade_fulfillments', ['company_id'], unique=False)
    op.create_index('ix_trade_fulfillments_source', 'trade_fulfillments', ['company_id', 'trade_document_id', 'id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillments_trade_document_id'), 'trade_fulfillments', ['trade_document_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillments_warehouse_document_id'), 'trade_fulfillments', ['warehouse_document_id'], unique=False)
    op.create_table('trade_fulfillment_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_id', sa.Integer(), nullable=False),
    sa.Column('trade_document_id', sa.Integer(), nullable=False),
    sa.Column('trade_document_line_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_document_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_document_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_trade_fulfillment_line_quantity_positive'),
    sa.ForeignKeyConstraint(['company_id', 'fulfillment_id', 'trade_document_id', 'warehouse_document_id'], ['trade_fulfillments.company_id', 'trade_fulfillments.id', 'trade_fulfillments.trade_document_id', 'trade_fulfillments.warehouse_document_id'], name='fk_trade_fulfillment_lines_fulfillment', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'trade_document_id', 'trade_document_line_id', 'product_id', 'warehouse_id'], ['trade_document_lines.company_id', 'trade_document_lines.trade_document_id', 'trade_document_lines.id', 'trade_document_lines.product_id', 'trade_document_lines.warehouse_id'], name='fk_trade_fulfillment_lines_trade_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_document_id', 'warehouse_document_line_id', 'product_id', 'warehouse_id'], ['document_lines.document_id', 'document_lines.id', 'document_lines.product_id', 'document_lines.warehouse_id'], name='fk_trade_fulfillment_lines_warehouse_target', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_document_line_id', name='uq_trade_fulfillment_lines_warehouse_document_line')
    )
    op.create_index(op.f('ix_trade_fulfillment_lines_company_id'), 'trade_fulfillment_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_fulfillment_id'), 'trade_fulfillment_lines', ['fulfillment_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_product_id'), 'trade_fulfillment_lines', ['product_id'], unique=False)
    op.create_index('ix_trade_fulfillment_lines_source', 'trade_fulfillment_lines', ['company_id', 'trade_document_line_id', 'id'], unique=False)
    op.create_index('ix_trade_fulfillment_lines_target_document', 'trade_fulfillment_lines', ['warehouse_document_id', 'id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_trade_document_id'), 'trade_fulfillment_lines', ['trade_document_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_trade_document_line_id'), 'trade_fulfillment_lines', ['trade_document_line_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_warehouse_document_id'), 'trade_fulfillment_lines', ['warehouse_document_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_warehouse_document_line_id'), 'trade_fulfillment_lines', ['warehouse_document_line_id'], unique=False)
    op.create_index(op.f('ix_trade_fulfillment_lines_warehouse_id'), 'trade_fulfillment_lines', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_fulfillment_lines_warehouse_id'), table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_warehouse_document_line_id'), table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_warehouse_document_id'), table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_trade_document_line_id'), table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_trade_document_id'), table_name='trade_fulfillment_lines')
    op.drop_index('ix_trade_fulfillment_lines_target_document', table_name='trade_fulfillment_lines')
    op.drop_index('ix_trade_fulfillment_lines_source', table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_product_id'), table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_fulfillment_id'), table_name='trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillment_lines_company_id'), table_name='trade_fulfillment_lines')
    op.drop_table('trade_fulfillment_lines')
    op.drop_index(op.f('ix_trade_fulfillments_warehouse_document_id'), table_name='trade_fulfillments')
    op.drop_index(op.f('ix_trade_fulfillments_trade_document_id'), table_name='trade_fulfillments')
    op.drop_index('ix_trade_fulfillments_source', table_name='trade_fulfillments')
    op.drop_index(op.f('ix_trade_fulfillments_company_id'), table_name='trade_fulfillments')
    op.drop_table('trade_fulfillments')
    op.drop_constraint('uq_document_lines_fulfillment_target', 'document_lines', type_='unique')
    op.drop_constraint('uq_documents_company_id_id_document_type', 'documents', type_='unique')
    # ### end Alembic commands ###
