"""add outbox lease fields

Revision ID: 19892558ab56
Revises: 964b751ba788
Create Date: 2026-08-21 19:48:27.586023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19892558ab56'
down_revision: Union[str, Sequence[str], None] = '964b751ba788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('claimed_by', sa.String(length=255), nullable=True))
    op.add_column('outbox_events', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('outbox_events', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_outbox_events_claimed_by'), 'outbox_events', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_outbox_events_lease_expires_at'), 'outbox_events', ['lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_lease_expires_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_claimed_by'), table_name='outbox_events')
    op.drop_column('outbox_events', 'lease_expires_at')
    op.drop_column('outbox_events', 'processing_started_at')
    op.drop_column('outbox_events', 'claimed_by')
    # ### end Alembic commands ###
