"""create trade documents

Revision ID: 1ed0e8211fc7
Revises: 13783d5f542a
Create Date: 2026-08-25 16:03:48.231424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed0e8211fc7'
down_revision: Union[str, Sequence[str], None] = '13783d5f542a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_contracts_company_counterparty_id', 'contracts', ['company_id', 'counterparty_id', 'id'])
    op.create_unique_constraint('uq_products_company_id_id', 'products', ['company_id', 'id'])
    op.create_unique_constraint('uq_warehouses_company_id_id', 'warehouses', ['company_id', 'id'])
    op.create_table('trade_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('sale', 'purchase', name='trade_direction_enum', native_enum=False), nullable=False),
    sa.Column('kind', sa.Enum('order', 'invoice', name='trade_document_kind_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'partially_fulfilled', 'fulfilled', 'cancelled', name='trade_document_status_enum', native_enum=False), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('payment_term_days', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("direction IN ('sale', 'purchase')", name='ck_trade_document_direction'),
    sa.CheckConstraint("kind IN ('order', 'invoice')", name='ck_trade_document_kind'),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'partially_fulfilled', 'fulfilled', 'cancelled')", name='ck_trade_document_status'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_trade_document_currency_code_length'),
    sa.CheckConstraint('payment_term_days >= 0', name='ck_trade_document_payment_term_days_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'counterparty_id', 'contract_id'], ['contracts.company_id', 'contracts.counterparty_id', 'contracts.id'], name='fk_trade_documents_company_counterparty_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'counterparty_id'], ['counterparties.company_id', 'counterparties.id'], name='fk_trade_documents_company_counterparty', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'direction', 'kind', 'number', name='uq_trade_document_company_direction_kind_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_trade_documents_company_id_id')
    )
    op.create_index(op.f('ix_trade_documents_company_id'), 'trade_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_contract_id'), 'trade_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_counterparty_id'), 'trade_documents', ['counterparty_id'], unique=False)
    op.create_table('trade_document_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade_document_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('line_number > 0', name='ck_trade_document_line_number_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_trade_document_line_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_trade_document_line_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'product_id'], ['products.company_id', 'products.id'], name='fk_trade_document_lines_company_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'trade_document_id'], ['trade_documents.company_id', 'trade_documents.id'], name='fk_trade_document_lines_company_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'warehouse_id'], ['warehouses.company_id', 'warehouses.id'], name='fk_trade_document_lines_company_warehouse', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_document_id', 'line_number', name='uq_trade_document_line_document_line_number')
    )
    op.create_index(op.f('ix_trade_document_lines_company_id'), 'trade_document_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_trade_document_lines_product_id'), 'trade_document_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_trade_document_lines_trade_document_id'), 'trade_document_lines', ['trade_document_id'], unique=False)
    op.create_index(op.f('ix_trade_document_lines_warehouse_id'), 'trade_document_lines', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_document_lines_warehouse_id'), table_name='trade_document_lines')
    op.drop_index(op.f('ix_trade_document_lines_trade_document_id'), table_name='trade_document_lines')
    op.drop_index(op.f('ix_trade_document_lines_product_id'), table_name='trade_document_lines')
    op.drop_index(op.f('ix_trade_document_lines_company_id'), table_name='trade_document_lines')
    op.drop_table('trade_document_lines')
    op.drop_index(op.f('ix_trade_documents_counterparty_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_contract_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_company_id'), table_name='trade_documents')
    op.drop_table('trade_documents')
    op.drop_constraint('uq_warehouses_company_id_id', 'warehouses', type_='unique')
    op.drop_constraint('uq_products_company_id_id', 'products', type_='unique')
    op.drop_constraint('uq_contracts_company_counterparty_id', 'contracts', type_='unique')
    # ### end Alembic commands ###
