"""add fixed asset opening balances

Revision ID: 2b49ee3de82f
Revises: 8e124c09a671
Create Date: 2026-09-27 22:02:59.888021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b49ee3de82f'
down_revision: Union[str, Sequence[str], None] = '8e124c09a671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('in_service_date', sa.Date(), nullable=False),
    sa.Column('original_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('previous_status', sa.String(length=23), nullable=False),
    sa.Column('previous_acquisition_date', sa.Date(), nullable=False),
    sa.Column('previous_in_service_date', sa.Date(), nullable=True),
    sa.Column('previous_original_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accumulated_depreciation <= original_cost', name='ck_fa_opening_accumulated_depreciation_not_above_cost'),
    sa.CheckConstraint('accumulated_depreciation >= 0', name='ck_fa_opening_accumulated_depreciation_nonnegative'),
    sa.CheckConstraint('in_service_date >= acquisition_date', name='ck_fa_opening_service_not_before_acquisition'),
    sa.CheckConstraint('original_cost > 0', name='ck_fa_opening_original_cost_positive'),
    sa.ForeignKeyConstraint(['company_id', 'opening_balance_id'], ['opening_balances.company_id', 'opening_balances.id'], name='fk_fa_opening_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fixed_asset_id'], ['fixed_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'opening_balance_id', 'fixed_asset_id', name='uq_fa_opening_source_asset')
    )
    op.create_index(op.f('ix_fixed_asset_opening_balances_fixed_asset_id'), 'fixed_asset_opening_balances', ['fixed_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixed_asset_opening_balances_fixed_asset_id'), table_name='fixed_asset_opening_balances')
    op.drop_table('fixed_asset_opening_balances')
    # ### end Alembic commands ###
