"""link tax recognition to tax credit evidence

Revision ID: 2dd0eaff8351
Revises: b8cad71d9a7e
Create Date: 2026-09-02 18:03:46.722710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd0eaff8351'
down_revision: Union[str, Sequence[str], None] = 'b8cad71d9a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_recognition_events', sa.Column('tax_credit_evidence_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tax_recognition_events_tax_credit_evidence_id'), 'tax_recognition_events', ['tax_credit_evidence_id'], unique=False)
    op.create_index('ix_tax_recognition_events_tax_credit_evidence_source', 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'tax_credit_evidence_id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL AND tax_credit_evidence_id IS NOT NULL'))
    op.create_foreign_key('fk_tax_recognition_events_company_tax_credit_evidence', 'tax_recognition_events', 'tax_credit_evidence', ['company_id', 'tax_credit_evidence_id', 'tax_calculation_id'], ['company_id', 'id', 'tax_calculation_id'], ondelete='RESTRICT')
    op.drop_constraint(
        'ck_tax_recognition_events_at_most_one_recognition_source',
        'tax_recognition_events',
        type_='check',
    )
    op.create_check_constraint(
        'ck_tax_recognition_events_at_most_one_recognition_source',
        'tax_recognition_events',
        "(invoice_fulfillment_allocation_id IS NULL OR payment_settlement_allocation_id IS NULL) AND (invoice_fulfillment_allocation_id IS NULL OR tax_credit_evidence_id IS NULL) AND (payment_settlement_allocation_id IS NULL OR tax_credit_evidence_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tax_recognition_events_company_tax_credit_evidence', 'tax_recognition_events', type_='foreignkey')
    op.drop_index('ix_tax_recognition_events_tax_credit_evidence_source', table_name='tax_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL AND tax_credit_evidence_id IS NOT NULL'))
    op.drop_index(op.f('ix_tax_recognition_events_tax_credit_evidence_id'), table_name='tax_recognition_events')
    op.drop_constraint(
        'ck_tax_recognition_events_at_most_one_recognition_source',
        'tax_recognition_events',
        type_='check',
    )
    op.create_check_constraint(
        'ck_tax_recognition_events_at_most_one_recognition_source',
        'tax_recognition_events',
        "invoice_fulfillment_allocation_id IS NULL OR payment_settlement_allocation_id IS NULL",
    )
    op.drop_column('tax_recognition_events', 'tax_credit_evidence_id')
    # ### end Alembic commands ###
