"""add fixed asset acquisition costs

Revision ID: 2f44d7201efe
Revises: e50a0439ab4c
Create Date: 2026-09-25 22:43:31.035189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f44d7201efe'
down_revision: Union[str, Sequence[str], None] = 'e50a0439ab4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_acquisition_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('cost_type', sa.Enum('acquisition', 'delivery', 'installation', 'other_direct', name='fixed_asset_acquisition_cost_type'), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_journal_entry_line_id', sa.Integer(), nullable=False),
    sa.Column('source_description', sa.String(length=255), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_faac_amount_positive'),
    sa.CheckConstraint('char_length(trim(request_key)) > 0', name='ck_faac_request_key_nonempty'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_of_id <> id', name='ck_faac_not_self_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'fixed_asset_id'], ['fixed_assets.company_id', 'fixed_assets.id'], name='fk_faac_company_asset', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id'], ['fixed_asset_acquisition_costs.company_id', 'fixed_asset_acquisition_costs.id'], name='fk_faac_company_reversal_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_journal_entry_line_id'], ['journal_entry_lines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_faac_company_id_id'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_faac_company_request_key')
    )
    op.create_index('ix_faac_company_asset', 'fixed_asset_acquisition_costs', ['company_id', 'fixed_asset_id', 'id'], unique=False)
    op.create_index('ix_faac_source_line', 'fixed_asset_acquisition_costs', ['source_journal_entry_line_id'], unique=False)
    op.create_index(op.f('ix_fixed_asset_acquisition_costs_company_id'), 'fixed_asset_acquisition_costs', ['company_id'], unique=False)
    op.create_index('uq_faac_reversal_of', 'fixed_asset_acquisition_costs', ['reversal_of_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_faac_reversal_of', table_name='fixed_asset_acquisition_costs', postgresql_where=sa.text('reversal_of_id IS NOT NULL'))
    op.drop_index(op.f('ix_fixed_asset_acquisition_costs_company_id'), table_name='fixed_asset_acquisition_costs')
    op.drop_index('ix_faac_source_line', table_name='fixed_asset_acquisition_costs')
    op.drop_index('ix_faac_company_asset', table_name='fixed_asset_acquisition_costs')
    op.drop_table('fixed_asset_acquisition_costs')
    # ### end Alembic commands ###
