"""add fixed asset depreciation

Revision ID: 31458c806d54
Revises: 2b49ee3de82f
Create Date: 2026-09-28 11:32:30.671337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31458c806d54'
down_revision: Union[str, Sequence[str], None] = '2b49ee3de82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_depreciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accumulated_after >= accumulated_before', name='ck_fa_depr_accum_order'),
    sa.CheckConstraint('accumulated_before >= 0', name='ck_fa_depr_accum_before_nonnegative'),
    sa.CheckConstraint('amount > 0', name='ck_fa_depr_amount_positive'),
    sa.CheckConstraint('period_end >= period_start', name='ck_fa_depr_period_order'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fixed_asset_id'], ['fixed_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['fixed_asset_depreciations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fixed_asset_id', 'period_start', 'period_end', name='uq_fa_depr_asset_period'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_fa_depr_company_request')
    )
    op.create_index(op.f('ix_fixed_asset_depreciations_company_id'), 'fixed_asset_depreciations', ['company_id'], unique=False)
    op.create_index(op.f('ix_fixed_asset_depreciations_fixed_asset_id'), 'fixed_asset_depreciations', ['fixed_asset_id'], unique=False)
    op.create_index(op.f('ix_fixed_asset_depreciations_posting_date'), 'fixed_asset_depreciations', ['posting_date'], unique=False)
    op.create_index(op.f('ix_fixed_asset_depreciations_reversal_of_id'), 'fixed_asset_depreciations', ['reversal_of_id'], unique=False)
    op.add_column('journal_entries', sa.Column('fixed_asset_depreciation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_journal_entries_fixed_asset_depreciation_id'), 'journal_entries', ['fixed_asset_depreciation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_fixed_asset_depreciation_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'fixed_asset_depreciation_id')
    op.drop_index(op.f('ix_fixed_asset_depreciations_reversal_of_id'), table_name='fixed_asset_depreciations')
    op.drop_index(op.f('ix_fixed_asset_depreciations_posting_date'), table_name='fixed_asset_depreciations')
    op.drop_index(op.f('ix_fixed_asset_depreciations_fixed_asset_id'), table_name='fixed_asset_depreciations')
    op.drop_index(op.f('ix_fixed_asset_depreciations_company_id'), table_name='fixed_asset_depreciations')
    op.drop_table('fixed_asset_depreciations')
    # ### end Alembic commands ###
