"""add fifo stock lots

Revision ID: 35e427fb5c59
Revises: 852d43704794
Create Date: 2026-08-18 20:57:14.605406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e427fb5c59'
down_revision: Union[str, Sequence[str], None] = '852d43704794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('source_document_line_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('original_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('original_quantity > 0', name='ck_stock_lot_original_quantity_positive'),
    sa.CheckConstraint('remaining_quantity <= original_quantity', name='ck_stock_lot_remaining_not_above_original'),
    sa.CheckConstraint('remaining_quantity >= 0', name='ck_stock_lot_remaining_quantity_nonnegative'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_stock_lot_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_line_id'], ['document_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_line_id', name='uq_stock_lot_source_document_line')
    )
    op.create_index('ix_stock_lot_fifo_lookup', 'stock_lots', ['company_id', 'product_id', 'warehouse_id', 'received_date', 'id'], unique=False)
    op.create_index(op.f('ix_stock_lots_company_id'), 'stock_lots', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_lots_received_date'), 'stock_lots', ['received_date'], unique=False)
    op.create_index(op.f('ix_stock_lots_source_document_id'), 'stock_lots', ['source_document_id'], unique=False)
    op.create_table('stock_lot_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('issue_document_id', sa.Integer(), nullable=False),
    sa.Column('issue_document_line_id', sa.Integer(), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_stock_lot_consumption_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_stock_lot_consumption_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_document_line_id'], ['document_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_document_line_id', 'stock_lot_id', name='uq_stock_lot_consumption_line_lot')
    )
    op.create_index('ix_stock_lot_consumption_document', 'stock_lot_consumptions', ['company_id', 'issue_document_id'], unique=False)
    op.create_index('ix_stock_lot_consumption_lot', 'stock_lot_consumptions', ['stock_lot_id'], unique=False)
    op.create_index(op.f('ix_stock_lot_consumptions_company_id'), 'stock_lot_consumptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_lot_consumptions_issue_document_id'), 'stock_lot_consumptions', ['issue_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_lot_consumptions_issue_document_id'), table_name='stock_lot_consumptions')
    op.drop_index(op.f('ix_stock_lot_consumptions_company_id'), table_name='stock_lot_consumptions')
    op.drop_index('ix_stock_lot_consumption_lot', table_name='stock_lot_consumptions')
    op.drop_index('ix_stock_lot_consumption_document', table_name='stock_lot_consumptions')
    op.drop_table('stock_lot_consumptions')
    op.drop_index(op.f('ix_stock_lots_source_document_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_received_date'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_company_id'), table_name='stock_lots')
    op.drop_index('ix_stock_lot_fifo_lookup', table_name='stock_lots')
    op.drop_table('stock_lots')
    # ### end Alembic commands ###
