"""add payroll salary slice time snapshots

Revision ID: 36e215ca4492
Revises: ba5bf40a8bc7
Create Date: 2026-10-02 18:53:29.777816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e215ca4492'
down_revision: Union[str, Sequence[str], None] = 'ba5bf40a8bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_input_salary_slices', sa.Column('scheduled_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('payroll_input_salary_slices', sa.Column('worked_minutes', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint('ck_payroll_salary_slices_scheduled_minutes_nonnegative', 'payroll_input_salary_slices', 'scheduled_minutes >= 0')
    op.create_check_constraint('ck_payroll_salary_slices_worked_minutes_nonnegative', 'payroll_input_salary_slices', 'worked_minutes >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_payroll_salary_slices_worked_minutes_nonnegative', 'payroll_input_salary_slices', type_='check')
    op.drop_constraint('ck_payroll_salary_slices_scheduled_minutes_nonnegative', 'payroll_input_salary_slices', type_='check')
    op.drop_column('payroll_input_salary_slices', 'worked_minutes')
    op.drop_column('payroll_input_salary_slices', 'scheduled_minutes')
    # ### end Alembic commands ###
