"""add payroll deduction accounting provenance

Revision ID: 383a1d9fd6a6
Revises: 6d09b64d5f35
Create Date: 2026-10-06 23:46:04.369646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383a1d9fd6a6'
down_revision: Union[str, Sequence[str], None] = '6d09b64d5f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('payroll_deduction_result_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_journal_entries_payroll_deduction_result_id'), 'journal_entries', ['payroll_deduction_result_id'], unique=False)
    op.create_index('uq_je_original_payroll_deduction_result', 'journal_entries', ['company_id', 'payroll_deduction_result_id'], unique=True, postgresql_where=sa.text('payroll_deduction_result_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.create_foreign_key('fk_je_company_payroll_deduction_result', 'journal_entries', 'payroll_deduction_results', ['company_id', 'payroll_deduction_result_id'], ['company_id', 'id'], ondelete='RESTRICT', use_alter=True)
    # C3 manual source exclusivity repair
    op.drop_constraint('ck_je_payroll_calculation_exclusive', 'journal_entries', type_='check')
    op.create_check_constraint('ck_je_payroll_calculation_exclusive', 'journal_entries', 'payroll_calculation_id IS NULL OR num_nonnulls(payroll_deduction_result_id,payroll_advance_id,payroll_disbursement_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    op.drop_constraint('ck_je_payroll_disbursement_exclusive', 'journal_entries', type_='check')
    op.create_check_constraint('ck_je_payroll_disbursement_exclusive', 'journal_entries', 'payroll_disbursement_id IS NULL OR num_nonnulls(payroll_deduction_result_id,payroll_advance_id,payroll_calculation_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    op.drop_constraint('ck_je_payroll_advance_exclusive', 'journal_entries', type_='check')
    op.create_check_constraint('ck_je_payroll_advance_exclusive', 'journal_entries', 'payroll_advance_id IS NULL OR num_nonnulls(payroll_deduction_result_id,payroll_calculation_id,payroll_disbursement_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    op.create_check_constraint('ck_je_payroll_deduction_result_exclusive', 'journal_entries', 'payroll_deduction_result_id IS NULL OR num_nonnulls(payroll_calculation_id,payroll_disbursement_id,payroll_advance_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM journal_entries WHERE payroll_deduction_result_id IS NOT NULL) THEN
            RAISE EXCEPTION 'Payroll deduction posting history must be preserved';
        END IF;
    END $$""")
    op.drop_constraint('ck_je_payroll_deduction_result_exclusive', 'journal_entries', type_='check')
    # C3 restore pre-deduction source checks
    op.drop_constraint('ck_je_payroll_calculation_exclusive', 'journal_entries', type_='check')
    op.drop_constraint('ck_je_payroll_disbursement_exclusive', 'journal_entries', type_='check')
    op.drop_constraint('ck_je_payroll_advance_exclusive', 'journal_entries', type_='check')
    op.create_check_constraint('ck_je_payroll_calculation_exclusive', 'journal_entries', 'payroll_calculation_id IS NULL OR num_nonnulls(payroll_advance_id,payroll_disbursement_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    op.create_check_constraint('ck_je_payroll_disbursement_exclusive', 'journal_entries', 'payroll_disbursement_id IS NULL OR num_nonnulls(payroll_advance_id,payroll_calculation_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    op.create_check_constraint('ck_je_payroll_advance_exclusive', 'journal_entries', 'payroll_advance_id IS NULL OR num_nonnulls(payroll_calculation_id,payroll_disbursement_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    op.drop_constraint('fk_je_company_payroll_deduction_result', 'journal_entries', type_='foreignkey')
    op.drop_index('uq_je_original_payroll_deduction_result', table_name='journal_entries', postgresql_where=sa.text('payroll_deduction_result_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.drop_index(op.f('ix_journal_entries_payroll_deduction_result_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'payroll_deduction_result_id')
    # ### end Alembic commands ###
