"""add vacation payroll line provenance

Revision ID: 3ac48a42b2b7
Revises: 45ebd7f03997
Create Date: 2026-10-07 09:16:03.173968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac48a42b2b7'
down_revision: Union[str, Sequence[str], None] = '45ebd7f03997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_calculation_lines', sa.Column('source_vacation_calculation_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_payroll_calculation_line_vacation', 'payroll_calculation_lines', 'payroll_vacation_calculations', ['company_id', 'source_vacation_calculation_id'], ['company_id', 'id'], ondelete='RESTRICT')

    op.drop_constraint(
        'ck_payroll_calculation_lines_type',
        'payroll_calculation_lines',
        type_='check',
    )
    op.drop_constraint(
        'ck_payroll_calculation_lines_rate_nonnegative',
        'payroll_calculation_lines',
        type_='check',
    )
    op.drop_constraint(
        'ck_payroll_calculation_lines_amount_by_type',
        'payroll_calculation_lines',
        type_='check',
    )

    op.create_check_constraint(
        'ck_payroll_calculation_lines_type',
        'payroll_calculation_lines',
        "line_type IN ('salary','manual_adjustment','supplement','vacation_pay')",
    )
    op.create_check_constraint(
        'ck_payroll_calculation_lines_rate_nonnegative',
        'payroll_calculation_lines',
        "(line_type IN ('salary','supplement','vacation_pay') AND rate >= 0) "
        "OR line_type = 'manual_adjustment'",
    )
    op.create_check_constraint(
        'ck_payroll_calculation_lines_amount_by_type',
        'payroll_calculation_lines',
        "(line_type IN ('salary','supplement','vacation_pay') AND amount >= 0) "
        "OR line_type = 'manual_adjustment'",
    )
    op.create_check_constraint(
        'ck_payroll_calculation_line_vacation_source',
        'payroll_calculation_lines',
        "(line_type = 'vacation_pay') = "
        "(source_vacation_calculation_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_payroll_calculation_line_vacation_source',
        'payroll_calculation_lines',
        type_='check',
    )

    op.drop_constraint(
        'ck_payroll_calculation_lines_amount_by_type',
        'payroll_calculation_lines',
        type_='check',
    )
    op.drop_constraint(
        'ck_payroll_calculation_lines_rate_nonnegative',
        'payroll_calculation_lines',
        type_='check',
    )
    op.drop_constraint(
        'ck_payroll_calculation_lines_type',
        'payroll_calculation_lines',
        type_='check',
    )

    op.create_check_constraint(
        'ck_payroll_calculation_lines_type',
        'payroll_calculation_lines',
        "line_type IN ('salary','manual_adjustment','supplement')",
    )
    op.create_check_constraint(
        'ck_payroll_calculation_lines_rate_nonnegative',
        'payroll_calculation_lines',
        "(line_type IN ('salary','supplement') AND rate >= 0) "
        "OR line_type = 'manual_adjustment'",
    )
    op.create_check_constraint(
        'ck_payroll_calculation_lines_amount_by_type',
        'payroll_calculation_lines',
        "(line_type IN ('salary','supplement') AND amount >= 0) "
        "OR line_type = 'manual_adjustment'",
    )

    op.drop_constraint(
        'fk_payroll_calculation_line_vacation',
        'payroll_calculation_lines',
        type_='foreignkey',
    )
    op.drop_column(
        'payroll_calculation_lines',
        'source_vacation_calculation_id',
    )
    # ### end Alembic commands ###
