"""add payroll period input foundation

Revision ID: 3fa9354d7a92
Revises: cbc034fccab3
Create Date: 2026-10-02 17:27:02.897781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa9354d7a92'
down_revision: Union[str, Sequence[str], None] = 'cbc034fccab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'finalized', name='payroll_period_status', native_enum=False), server_default='draft', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('finalized_by', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'draft'\n                AND finalized_by IS NULL\n                AND finalized_at IS NULL\n            )\n            OR\n            (\n                status = 'finalized'\n                AND finalized_by IS NOT NULL\n                AND finalized_at IS NOT NULL\n            )\n            ", name='ck_payroll_periods_lifecycle_metadata'),
    sa.CheckConstraint("status IN ('draft','finalized')", name='ck_payroll_periods_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_payroll_periods_date_range'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_payroll_periods_month'),
    sa.CheckConstraint('year > 0', name='ck_payroll_periods_year_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_periods_company_id_id'),
    sa.UniqueConstraint('company_id', 'year', 'month', name='uq_payroll_periods_company_year_month')
    )
    op.create_index('ix_payroll_periods_company_dates', 'payroll_periods', ['company_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_payroll_periods_company_status', 'payroll_periods', ['company_id', 'status'], unique=False)
    op.create_table('payroll_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('worked_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leave_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sick_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('manual_adjustment_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('manual_adjustment_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('system', 'manual', name='payroll_input_source', native_enum=False), server_default='system', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("manual_adjustment_amount = 0 OR length(trim(coalesce(manual_adjustment_reason, ''))) > 0", name='ck_payroll_inputs_adjustment_reason'),
    sa.CheckConstraint("source IN ('system','manual')", name='ck_payroll_inputs_source'),
    sa.CheckConstraint('leave_days >= 0', name='ck_payroll_inputs_leave_days_nonnegative'),
    sa.CheckConstraint('scheduled_minutes >= 0', name='ck_payroll_inputs_scheduled_minutes_nonnegative'),
    sa.CheckConstraint('sick_days >= 0', name='ck_payroll_inputs_sick_days_nonnegative'),
    sa.CheckConstraint('worked_minutes >= 0', name='ck_payroll_inputs_worked_minutes_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_inputs_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_period_id'], ['payroll_periods.company_id', 'payroll_periods.id'], name='fk_payroll_inputs_company_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_inputs_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_period_id', 'employment_contract_id', name='uq_payroll_inputs_company_period_contract')
    )
    op.create_index('ix_payroll_inputs_company_contract', 'payroll_inputs', ['company_id', 'employment_contract_id'], unique=False)
    op.create_index('ix_payroll_inputs_company_period', 'payroll_inputs', ['company_id', 'payroll_period_id'], unique=False)
    op.create_table('payroll_input_salary_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_input_id', sa.Integer(), nullable=False),
    sa.Column('salary_rate_id', sa.Integer(), nullable=False),
    sa.Column('salary_rate_type', sa.String(length=20), nullable=False),
    sa.Column('salary_rate_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("salary_rate_type IN ('monthly','hourly')", name='ck_payroll_salary_slices_rate_type'),
    sa.CheckConstraint('char_length(currency_code) = 3 AND currency_code = upper(currency_code)', name='ck_payroll_salary_slices_currency'),
    sa.CheckConstraint('effective_to >= effective_from', name='ck_payroll_salary_slices_date_range'),
    sa.CheckConstraint('salary_rate_amount > 0', name='ck_payroll_salary_slices_amount_positive'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_input_id'], ['payroll_inputs.company_id', 'payroll_inputs.id'], name='fk_payroll_salary_slices_company_input', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'salary_rate_id'], ['employee_salary_rates.company_id', 'employee_salary_rates.id'], name='fk_payroll_salary_slices_company_rate', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_input_salary_slices_company_id_id')
    )
    op.create_index('ix_payroll_salary_slices_company_input', 'payroll_input_salary_slices', ['company_id', 'payroll_input_id', 'effective_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payroll_salary_slices_company_input', table_name='payroll_input_salary_slices')
    op.drop_table('payroll_input_salary_slices')
    op.drop_index('ix_payroll_inputs_company_period', table_name='payroll_inputs')
    op.drop_index('ix_payroll_inputs_company_contract', table_name='payroll_inputs')
    op.drop_table('payroll_inputs')
    op.drop_index('ix_payroll_periods_company_status', table_name='payroll_periods')
    op.drop_index('ix_payroll_periods_company_dates', table_name='payroll_periods')
    op.drop_table('payroll_periods')
    # ### end Alembic commands ###
