"""add leave request foundation

Revision ID: 3ff0ec5e17e5
Revises: 942689c3ff90
Create Date: 2026-10-02 16:58:13.906694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff0ec5e17e5'
down_revision: Union[str, Sequence[str], None] = '942689c3ff90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('annual', 'sick', 'unpaid', 'other', name='leave_type', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_request_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'pending'\n                AND approved_by IS NULL\n                AND approved_at IS NULL\n                AND rejected_by IS NULL\n                AND rejected_at IS NULL\n                AND cancelled_by IS NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'approved'\n                AND approved_by IS NOT NULL\n                AND approved_at IS NOT NULL\n                AND rejected_by IS NULL\n                AND rejected_at IS NULL\n                AND cancelled_by IS NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'rejected'\n                AND approved_by IS NULL\n                AND approved_at IS NULL\n                AND rejected_by IS NOT NULL\n                AND rejected_at IS NOT NULL\n                AND cancelled_by IS NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'cancelled'\n                AND cancelled_by IS NOT NULL\n                AND cancelled_at IS NOT NULL\n                AND rejected_by IS NULL\n                AND rejected_at IS NULL\n            )\n            ", name='ck_leave_requests_lifecycle_metadata'),
    sa.CheckConstraint("leave_type IN ('annual','sick','unpaid','other')", name='ck_leave_requests_type'),
    sa.CheckConstraint("status IN ('pending','approved','rejected','cancelled')", name='ck_leave_requests_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_requests_date_range'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_leave_requests_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_leave_requests_company_id_id')
    )
    op.create_index('ix_leave_requests_company_contract_dates', 'leave_requests', ['company_id', 'employment_contract_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_leave_requests_company_status', 'leave_requests', ['company_id', 'status'], unique=False)
    op.add_column('attendance_records', sa.Column('leave_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_attendance_records_company_leave_request', 'attendance_records', 'leave_requests', ['company_id', 'leave_request_id'], ['company_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attendance_records_company_leave_request', 'attendance_records', type_='foreignkey')
    op.drop_column('attendance_records', 'leave_request_id')
    op.drop_index('ix_leave_requests_company_status', table_name='leave_requests')
    op.drop_index('ix_leave_requests_company_contract_dates', table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
