"""add payroll vacation financial foundation

Revision ID: 45ebd7f03997
Revises: cc1d6654ac2b
Create Date: 2026-10-07 09:10:57.052604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ebd7f03997'
down_revision: Union[str, Sequence[str], None] = 'cc1d6654ac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_vacation_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('leave_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_period_start', sa.Date(), nullable=False),
    sa.Column('reference_period_end', sa.Date(), nullable=False),
    sa.Column('eligible_earnings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('eligible_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_daily_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('vacation_pay_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='UAH', nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=100), nullable=False),
    sa.Column('calculated_by', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency_code = 'UAH'", name='ck_payroll_vacation_calculation_currency'),
    sa.CheckConstraint('average_daily_amount >= 0', name='ck_payroll_vacation_calculation_average'),
    sa.CheckConstraint('eligible_days > 0', name='ck_payroll_vacation_calculation_eligible_days'),
    sa.CheckConstraint('eligible_earnings >= 0', name='ck_payroll_vacation_calculation_earnings'),
    sa.CheckConstraint('leave_days > 0', name='ck_payroll_vacation_calculation_leave_days'),
    sa.CheckConstraint('length(trim(rule_code)) > 0', name='ck_payroll_vacation_calculation_rule_code'),
    sa.CheckConstraint('length(trim(rule_version)) > 0', name='ck_payroll_vacation_calculation_rule_version'),
    sa.CheckConstraint('reference_period_end >= reference_period_start', name='ck_payroll_vacation_calculation_reference_period'),
    sa.CheckConstraint('vacation_pay_amount >= 0', name='ck_payroll_vacation_calculation_amount'),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_vacation_calculation_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'leave_request_id'], ['leave_requests.company_id', 'leave_requests.id'], name='fk_payroll_vacation_calculation_leave', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_vacation_calculations_company_id_id'),
    sa.UniqueConstraint('company_id', 'leave_request_id', name='uq_payroll_vacation_calculations_leave_request')
    )
    op.create_table('payroll_vacation_calculation_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacation_calculation_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_period_start', sa.Date(), nullable=True),
    sa.Column('source_period_end', sa.Date(), nullable=True),
    sa.Column('earnings_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('eligible_days', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('earnings_history','payroll_calculation','leave_opening')", name='ck_payroll_vacation_source_type'),
    sa.CheckConstraint('earnings_amount >= 0', name='ck_payroll_vacation_source_earnings'),
    sa.CheckConstraint('eligible_days >= 0', name='ck_payroll_vacation_source_days'),
    sa.CheckConstraint('source_id > 0', name='ck_payroll_vacation_source_id'),
    sa.ForeignKeyConstraint(['company_id', 'vacation_calculation_id'], ['payroll_vacation_calculations.company_id', 'payroll_vacation_calculations.id'], name='fk_payroll_vacation_source_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_vacation_sources_company_id_id'),
    sa.UniqueConstraint('company_id', 'vacation_calculation_id', 'source_type', 'source_id', name='uq_payroll_vacation_sources_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_vacation_calculation_sources')
    op.drop_table('payroll_vacation_calculations')
    # ### end Alembic commands ###
