"""add payroll payslip foundation

Revision ID: 4b9db9df2485
Revises: 864b767fc1c7
Create Date: 2026-10-03 10:51:12.406812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9db9df2485'
down_revision: Union[str, Sequence[str], None] = '864b767fc1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('payroll_statutory_result_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=100), nullable=False),
    sa.Column('employee_first_name', sa.String(length=100), nullable=False),
    sa.Column('employee_last_name', sa.String(length=100), nullable=False),
    sa.Column('employee_middle_name', sa.String(length=100), nullable=True),
    sa.Column('employee_tax_number', sa.String(length=50), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employee_withholding_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employer_contribution_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency_code ~ '^[A-Z]{3}$'", name='ck_payroll_payslips_currency'),
    sa.CheckConstraint('employee_withholding_amount >= 0', name='ck_payroll_payslips_employee_withholding_nonnegative'),
    sa.CheckConstraint('employer_contribution_amount >= 0', name='ck_payroll_payslips_employer_contribution_nonnegative'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_payroll_payslips_gross_nonnegative'),
    sa.CheckConstraint('length(btrim(contract_number)) > 0', name='ck_payroll_payslips_contract_number_nonempty'),
    sa.CheckConstraint('length(btrim(employee_first_name)) > 0', name='ck_payroll_payslips_employee_first_name_nonempty'),
    sa.CheckConstraint('length(btrim(employee_last_name)) > 0', name='ck_payroll_payslips_employee_last_name_nonempty'),
    sa.CheckConstraint('length(btrim(employee_number)) > 0', name='ck_payroll_payslips_employee_number_nonempty'),
    sa.CheckConstraint('net_amount = gross_amount - employee_withholding_amount', name='ck_payroll_payslips_net_reconciliation'),
    sa.CheckConstraint('net_amount >= 0', name='ck_payroll_payslips_net_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'employee_id'], ['employees.company_id', 'employees.id'], name='fk_payroll_payslips_company_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_payslips_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_calculation_id'], ['payroll_calculations.company_id', 'payroll_calculations.id'], name='fk_payroll_payslips_company_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_period_id'], ['payroll_periods.company_id', 'payroll_periods.id'], name='fk_payroll_payslips_company_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_statutory_result_id'], ['payroll_statutory_results.company_id', 'payroll_statutory_results.id'], name='fk_payroll_payslips_company_statutory_result', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_payslips_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_calculation_id', name='uq_payroll_payslips_company_calculation')
    )
    op.create_index(op.f('ix_payroll_payslips_company_id'), 'payroll_payslips', ['company_id'], unique=False)
    op.create_table('payroll_payslip_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_payslip_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('line_kind', sa.String(length=32), nullable=False),
    sa.Column('component_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('source_payroll_calculation_line_id', sa.Integer(), nullable=True),
    sa.Column('source_payroll_statutory_result_line_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(\n                line_kind = 'earning'\n                AND source_payroll_calculation_line_id IS NOT NULL\n                AND source_payroll_statutory_result_line_id IS NULL\n            ) OR (\n                line_kind IN ('employee_withholding','employer_contribution')\n                AND source_payroll_calculation_line_id IS NULL\n                AND source_payroll_statutory_result_line_id IS NOT NULL\n            )", name='ck_payroll_payslip_lines_source_by_kind'),
    sa.CheckConstraint("currency_code ~ '^[A-Z]{3}$'", name='ck_payroll_payslip_lines_currency'),
    sa.CheckConstraint("line_kind IN ('earning','employee_withholding','employer_contribution')", name='ck_payroll_payslip_lines_kind'),
    sa.CheckConstraint("line_kind = 'earning' OR amount >= 0", name='ck_payroll_payslip_lines_amount_by_kind'),
    sa.CheckConstraint('length(btrim(component_code)) > 0', name='ck_payroll_payslip_lines_component_nonempty'),
    sa.CheckConstraint('line_no > 0', name='ck_payroll_payslip_lines_line_no_positive'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_payslip_id'], ['payroll_payslips.company_id', 'payroll_payslips.id'], name='fk_payroll_payslip_lines_company_payslip', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'source_payroll_calculation_line_id'], ['payroll_calculation_lines.company_id', 'payroll_calculation_lines.id'], name='fk_payroll_payslip_lines_company_calculation_line', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_payroll_statutory_result_line_id'], ['payroll_statutory_result_lines.id'], name='fk_payroll_payslip_lines_statutory_line', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_payslip_lines_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_payslip_id', 'line_no', name='uq_payroll_payslip_lines_payslip_line_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_payslip_lines')
    op.drop_index(op.f('ix_payroll_payslips_company_id'), table_name='payroll_payslips')
    op.drop_table('payroll_payslips')
    # ### end Alembic commands ###
