"""add user company role fields

Revision ID: 4c1907cbee12
Revises: 7c32753f2e1b
Create Date: 2026-08-14 19:35:01.936114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1907cbee12'
down_revision: Union[str, Sequence[str], None] = '7c32753f2e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_company_roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_company_roles', sa.Column('assigned_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_company_roles', 'assigned_at')
    op.drop_column('user_company_roles', 'is_active')
    # ### end Alembic commands ###
