"""add moving average movements

Revision ID: 5302a1c21aa7
Revises: 88fb870cf382
Create Date: 2026-08-19 14:40:21.373138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5302a1c21aa7'
down_revision: Union[str, Sequence[str], None] = '88fb870cf382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moving_average_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('receipt', 'issue', 'adjustment', 'reversal', name='moving_average_movement_type_enum', native_enum=False), nullable=False),
    sa.Column(
    'movement_date',
    sa.Date(),
    nullable=False,
),
    sa.Column('quantity_delta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('value_delta', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balance_quantity_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_value_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_unit_cost_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('average_unit_cost_after >= 0', name='ck_moving_average_movement_average_unit_cost_after_nonnegative'),
    sa.CheckConstraint('balance_quantity_after >= 0', name='ck_moving_average_movement_balance_quantity_after_nonnegative'),
    sa.CheckConstraint('balance_value_after >= 0', name='ck_moving_average_movement_balance_value_after_nonnegative'),
sa.CheckConstraint(
    'quantity_delta != 0 OR value_delta != 0',
    name='ck_moving_average_movement_nonzero_change',
),
    sa.CheckConstraint('unit_cost >= 0', name='ck_moving_average_movement_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_line_id'], ['document_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['moving_average_movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reversal_of_id', name='uq_moving_average_movement_reversal_of')
    )
    op.create_index(op.f('ix_moving_average_movements_company_id'), 'moving_average_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_moving_average_movements_document_id'), 'moving_average_movements', ['document_id'], unique=False)
    op.create_index(op.f('ix_moving_average_movements_document_line_id'), 'moving_average_movements', ['document_line_id'], unique=False)
    op.create_index(op.f('ix_moving_average_movements_product_id'), 'moving_average_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_moving_average_movements_reversal_of_id'), 'moving_average_movements', ['reversal_of_id'], unique=False)
    op.create_index(op.f('ix_moving_average_movements_warehouse_id'), 'moving_average_movements', ['warehouse_id'], unique=False)
    op.create_index(
    op.f(
        'ix_moving_average_movements_movement_date'
    ),
    'moving_average_movements',
    ['movement_date'],
    unique=False,
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f(
            "ix_moving_average_movements_movement_date"
        ),
        table_name="moving_average_movements",
    )

    op.drop_index(
        op.f(
            "ix_moving_average_movements_warehouse_id"
        ),
        table_name="moving_average_movements",
    )

    op.drop_index(
        op.f(
            "ix_moving_average_movements_reversal_of_id"
        ),
        table_name="moving_average_movements",
    )

    op.drop_index(
        op.f(
            "ix_moving_average_movements_product_id"
        ),
        table_name="moving_average_movements",
    )

    op.drop_index(
        op.f(
            "ix_moving_average_movements_document_line_id"
        ),
        table_name="moving_average_movements",
    )

    op.drop_index(
        op.f(
            "ix_moving_average_movements_document_id"
        ),
        table_name="moving_average_movements",
    )

    op.drop_index(
        op.f(
            "ix_moving_average_movements_company_id"
        ),
        table_name="moving_average_movements",
    )

    op.drop_table(
        "moving_average_movements"
    )
