"""add recalculation lease fields

Revision ID: 61b4a1c94429
Revises: d970587f9d31
Create Date: 2026-08-22 17:21:01.240275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b4a1c94429'
down_revision: Union[str, Sequence[str], None] = 'd970587f9d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recalculation_requests', sa.Column('claimed_by', sa.String(length=255), nullable=True))
    op.add_column('recalculation_requests', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recalculation_requests_lease_expires_at'), 'recalculation_requests', ['lease_expires_at'], unique=False)
    op.create_index('ix_recalculation_requests_status_lease', 'recalculation_requests', ['status', 'lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recalculation_requests_status_lease', table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_lease_expires_at'), table_name='recalculation_requests')
    op.drop_column('recalculation_requests', 'lease_expires_at')
    op.drop_column('recalculation_requests', 'claimed_by')
    # ### end Alembic commands ###
