"""add payroll statutory base provenance

Revision ID: 66dbc02f1c35
Revises: 5b3e69885978
Create Date: 2026-10-07 12:13:10.575136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dbc02f1c35'
down_revision: Union[str, Sequence[str], None] = '5b3e69885978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_statutory_result_lines', sa.Column('source_tax_profile_id', sa.Integer(), nullable=True))
    op.add_column('payroll_statutory_result_lines', sa.Column('source_base_rule_id', sa.Integer(), nullable=True))
    op.add_column('payroll_statutory_result_lines', sa.Column('gross_base_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('payroll_statutory_result_lines', sa.Column('benefit_amount_applied', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('payroll_statutory_result_lines', sa.Column('minimum_base_amount_applied', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('payroll_statutory_result_lines', sa.Column('maximum_base_amount_applied', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('payroll_statutory_result_lines', sa.Column('exemption_applied', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('payroll_statutory_result_lines', sa.Column('base_rule_code', sa.String(length=100), nullable=True))
    op.add_column('payroll_statutory_result_lines', sa.Column('base_rule_version', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_payroll_statutory_result_lines_company_tax_profile', 'payroll_statutory_result_lines', 'payroll_employee_tax_profiles', ['company_id', 'source_tax_profile_id'], ['company_id', 'id'])
    op.create_foreign_key('fk_payroll_statutory_result_lines_company_base_rule', 'payroll_statutory_result_lines', 'payroll_statutory_base_rules', ['company_id', 'source_base_rule_id'], ['company_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payroll_statutory_result_lines_company_base_rule', 'payroll_statutory_result_lines', type_='foreignkey')
    op.drop_constraint('fk_payroll_statutory_result_lines_company_tax_profile', 'payroll_statutory_result_lines', type_='foreignkey')
    op.drop_column('payroll_statutory_result_lines', 'base_rule_version')
    op.drop_column('payroll_statutory_result_lines', 'base_rule_code')
    op.drop_column('payroll_statutory_result_lines', 'exemption_applied')
    op.drop_column('payroll_statutory_result_lines', 'maximum_base_amount_applied')
    op.drop_column('payroll_statutory_result_lines', 'minimum_base_amount_applied')
    op.drop_column('payroll_statutory_result_lines', 'benefit_amount_applied')
    op.drop_column('payroll_statutory_result_lines', 'gross_base_amount')
    op.drop_column('payroll_statutory_result_lines', 'source_base_rule_id')
    op.drop_column('payroll_statutory_result_lines', 'source_tax_profile_id')
    # ### end Alembic commands ###
