"""add moving average balance and increase inventory cost precision

Revision ID: 6ea25f081a83
Revises: eb070f26955f
Create Date: 2026-08-19 13:55:13.415802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea25f081a83'
down_revision: Union[str, Sequence[str], None] = 'eb070f26955f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moving_average_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column(
    'inventory_value',
    sa.Numeric(precision=20, scale=8),
    nullable=False,
),
    sa.Column('average_unit_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('average_unit_cost >= 0', name='ck_moving_average_balance_average_unit_cost_nonnegative'),
    sa.CheckConstraint('inventory_value >= 0', name='ck_moving_average_balance_inventory_value_nonnegative'),
    sa.CheckConstraint('quantity >= 0', name='ck_moving_average_balance_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_id', 'warehouse_id', name='uq_moving_average_balance_company_product_warehouse')
    )
    op.create_index(op.f('ix_moving_average_balances_company_id'), 'moving_average_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_moving_average_balances_product_id'), 'moving_average_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_moving_average_balances_warehouse_id'), 'moving_average_balances', ['warehouse_id'], unique=False)
    op.alter_column('inventory_cost_entries', 'unit_cost',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_cost_entries', 'unit_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.drop_index(op.f('ix_moving_average_balances_warehouse_id'), table_name='moving_average_balances')
    op.drop_index(op.f('ix_moving_average_balances_product_id'), table_name='moving_average_balances')
    op.drop_index(op.f('ix_moving_average_balances_company_id'), table_name='moving_average_balances')
    op.drop_table('moving_average_balances')
    # ### end Alembic commands ###
