"""add fixed asset disposal lifecycle

Revision ID: 739f64c150c1
Revises: a33efad6aeaa
Create Date: 2026-09-28 16:20:12.262542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739f64c150c1'
down_revision: Union[str, Sequence[str], None] = 'a33efad6aeaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_disposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('original_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('carrying_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=False),
    sa.Column('disposal_account_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('accumulated_depreciation <= original_cost', name='ck_fad_accumulated_le_cost'),
    sa.CheckConstraint('accumulated_depreciation >= 0', name='ck_fad_accumulated_nonnegative'),
    sa.CheckConstraint('carrying_amount >= 0', name='ck_fad_carrying_nonnegative'),
    sa.CheckConstraint('original_cost >= 0', name='ck_fad_original_cost_nonnegative'),
    sa.CheckConstraint('salvage_value >= 0', name='ck_fad_salvage_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'disposal_account_id'], ['accounts.company_id', 'accounts.id'], name='fk_fad_company_disposal_account'),
    sa.ForeignKeyConstraint(['company_id', 'fixed_asset_id'], ['fixed_assets.company_id', 'fixed_assets.id'], name='fk_fad_company_asset'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id'], ['fixed_asset_disposals.company_id', 'fixed_asset_disposals.id'], name='fk_fad_company_reversal'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_fad_company_id_id'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_fad_company_request_key'),
    sa.UniqueConstraint('reversal_of_id', name='uq_fad_reversal_of')
    )
    op.create_index('ix_fad_company_asset', 'fixed_asset_disposals', ['company_id', 'fixed_asset_id'], unique=False)
    op.add_column('journal_entries', sa.Column('fixed_asset_disposal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_journal_entries_fixed_asset_disposal_id'), 'journal_entries', ['fixed_asset_disposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_fixed_asset_disposal_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'fixed_asset_disposal_id')
    op.drop_index('ix_fad_company_asset', table_name='fixed_asset_disposals')
    op.drop_table('fixed_asset_disposals')
    # ### end Alembic commands ###
