"""add fixed asset commissioning lifecycle

Revision ID: 760e17482bce
Revises: 2f44d7201efe
Create Date: 2026-09-26 19:23:45.739634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760e17482bce'
down_revision: Union[str, Sequence[str], None] = '2f44d7201efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_commissionings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(request_key)) > 0', name='ck_facomm_request_key_nonempty'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_of_id <> id', name='ck_facomm_no_self_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'fixed_asset_id'], ['fixed_assets.company_id', 'fixed_assets.id'], name='fk_facomm_company_asset', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id'], ['fixed_asset_commissionings.company_id', 'fixed_asset_commissionings.id'], name='fk_facomm_company_reversal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_facomm_company_id'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_facomm_company_request_key')
    )
    op.create_index('ix_facomm_company_asset', 'fixed_asset_commissionings', ['company_id', 'fixed_asset_id'], unique=False)
    op.create_index(op.f('ix_fixed_asset_commissionings_company_id'), 'fixed_asset_commissionings', ['company_id'], unique=False)
    op.create_index('uq_facomm_reversal_of', 'fixed_asset_commissionings', ['reversal_of_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NOT NULL'))
    op.add_column('journal_entries', sa.Column('fixed_asset_commissioning_id', sa.Integer(), nullable=True))
    op.create_index('ix_je_fixed_asset_commissioning', 'journal_entries', ['fixed_asset_commissioning_id'], unique=False)
    op.create_index('uq_je_fixed_asset_commissioning_original', 'journal_entries', ['fixed_asset_commissioning_id'], unique=True, postgresql_where=sa.text('fixed_asset_commissioning_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.create_foreign_key('fk_je_company_fixed_asset_commissioning', 'journal_entries', 'fixed_asset_commissionings', ['company_id', 'fixed_asset_commissioning_id'], ['company_id', 'id'], ondelete='RESTRICT', use_alter=True)
    # 12.4 MANUAL CHECK-CONSTRAINT ALIGNMENT
    op.drop_constraint(
        "ck_je_year_end_exclusive",
        "journal_entries",
        type_="check",
    )
    op.create_check_constraint(
        "ck_je_year_end_exclusive",
        "journal_entries",
        'year_end_closing_id IS NULL OR num_nonnulls(fixed_asset_commissioning_id,document_id,payment_id,payment_settlement_allocation_id,tax_recognition_event_id,sales_recognition_event_id,vat_advance_bridge_event_id,input_vat_fulfillment_bridge_event_id,supplier_advance_clearing_event_id,customer_advance_clearing_event_id,sales_return_recognition_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_ma_replay_event_id,sales_return_cost_restoration_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_return_input_vat_credit_correction_event_id,purchase_value_correction_vat_adjustment_event_id,purchase_value_correction_input_vat_credit_correction_event_id,opening_balance_id,tax_invoice_correction_line_id) = 0',
    )
    op.drop_constraint(
        "ck_je_rk_exclusive",
        "journal_entries",
        type_="check",
    )
    op.create_check_constraint(
        "ck_je_rk_exclusive",
        "journal_entries",
        'tax_invoice_correction_line_id IS NULL OR num_nonnulls(fixed_asset_commissioning_id,document_id,payment_id,payment_settlement_allocation_id,tax_recognition_event_id,sales_recognition_event_id,vat_advance_bridge_event_id,input_vat_fulfillment_bridge_event_id,supplier_advance_clearing_event_id,customer_advance_clearing_event_id,sales_return_recognition_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_ma_replay_event_id,sales_return_cost_restoration_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_return_input_vat_credit_correction_event_id,purchase_value_correction_vat_adjustment_event_id,purchase_value_correction_input_vat_credit_correction_event_id,opening_balance_id) = 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # 12.4 MANUAL CHECK-CONSTRAINT ALIGNMENT DOWNGRADE
    op.drop_constraint(
        "ck_je_year_end_exclusive",
        "journal_entries",
        type_="check",
    )
    op.create_check_constraint(
        "ck_je_year_end_exclusive",
        "journal_entries",
        'year_end_closing_id IS NULL OR num_nonnulls(document_id, payment_id, payment_settlement_allocation_id, tax_recognition_event_id, sales_recognition_event_id, vat_advance_bridge_event_id, input_vat_fulfillment_bridge_event_id, supplier_advance_clearing_event_id, customer_advance_clearing_event_id, sales_return_recognition_event_id, purchase_value_correction_fifo_impact_event_id, purchase_value_correction_ma_replay_event_id, sales_return_cost_restoration_event_id, purchase_return_recognition_event_id, purchase_return_vat_adjustment_event_id, purchase_return_input_vat_credit_correction_event_id, purchase_value_correction_vat_adjustment_event_id, purchase_value_correction_input_vat_credit_correction_event_id, opening_balance_id, tax_invoice_correction_line_id) = 0',
    )
    op.drop_constraint(
        "ck_je_rk_exclusive",
        "journal_entries",
        type_="check",
    )
    op.create_check_constraint(
        "ck_je_rk_exclusive",
        "journal_entries",
        'tax_invoice_correction_line_id IS NULL OR num_nonnulls(document_id, payment_id, payment_settlement_allocation_id, tax_recognition_event_id, sales_recognition_event_id, vat_advance_bridge_event_id, input_vat_fulfillment_bridge_event_id, supplier_advance_clearing_event_id, customer_advance_clearing_event_id, sales_return_recognition_event_id, purchase_value_correction_fifo_impact_event_id, purchase_value_correction_ma_replay_event_id, sales_return_cost_restoration_event_id, purchase_return_recognition_event_id, purchase_return_vat_adjustment_event_id, purchase_return_input_vat_credit_correction_event_id, purchase_value_correction_vat_adjustment_event_id, purchase_value_correction_input_vat_credit_correction_event_id, opening_balance_id) = 0',
    )
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_je_company_fixed_asset_commissioning', 'journal_entries', type_='foreignkey')
    op.drop_index('uq_je_fixed_asset_commissioning_original', table_name='journal_entries', postgresql_where=sa.text('fixed_asset_commissioning_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.drop_index('ix_je_fixed_asset_commissioning', table_name='journal_entries')
    op.drop_column('journal_entries', 'fixed_asset_commissioning_id')
    op.drop_index('uq_facomm_reversal_of', table_name='fixed_asset_commissionings', postgresql_where=sa.text('reversal_of_id IS NOT NULL'))
    op.drop_index(op.f('ix_fixed_asset_commissionings_company_id'), table_name='fixed_asset_commissionings')
    op.drop_index('ix_facomm_company_asset', table_name='fixed_asset_commissionings')
    op.drop_table('fixed_asset_commissionings')
    # ### end Alembic commands ###
