"""add payments and settlement allocations

Revision ID: 84019bf78180
Revises: b0a3b206bd82
Create Date: 2026-08-29 16:10:48.673564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84019bf78180'
down_revision: Union[str, Sequence[str], None] = 'b0a3b206bd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='payment_direction_enum', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled', name='payment_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'draft' AND confirmed_at IS NULL AND cancelled_by IS NULL AND cancelled_at IS NULL) OR (status = 'confirmed' AND confirmed_at IS NOT NULL AND cancelled_by IS NULL AND cancelled_at IS NULL) OR (status = 'cancelled' AND cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL)", name='ck_payments_lifecycle_state'),
    sa.CheckConstraint("direction IN ('incoming', 'outgoing')", name='ck_payments_direction'),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'cancelled')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_payments_currency_code_length'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'counterparty_id', 'contract_id'], ['contracts.company_id', 'contracts.counterparty_id', 'contracts.id'], name='fk_payments_company_counterparty_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'counterparty_id'], ['counterparties.company_id', 'counterparties.id'], name='fk_payments_company_counterparty', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'direction', 'number', name='uq_payments_company_direction_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payments_company_id_id')
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_contract_id'), 'payments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payments_counterparty_id'), 'payments', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_payments_currency_code'), 'payments', ['currency_code'], unique=False)
    op.create_index(op.f('ix_payments_direction'), 'payments', ['direction'], unique=False)
    op.create_index(op.f('ix_payments_external_reference'), 'payments', ['external_reference'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_settlement_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('open_item_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'reversed', name='payment_settlement_allocation_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'active' AND reversed_by IS NULL AND reversed_at IS NULL) OR (status = 'reversed' AND reversed_by IS NOT NULL AND reversed_at IS NOT NULL)", name='ck_payment_settlement_allocations_reversal_state'),
    sa.CheckConstraint("status IN ('active', 'reversed')", name='ck_payment_settlement_allocations_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_settlement_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['company_id', 'open_item_id'], ['counterparty_open_items.company_id', 'counterparty_open_items.id'], name='fk_payment_settlement_allocations_open_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payment_id'], ['payments.company_id', 'payments.id'], name='fk_payment_settlement_allocations_payment', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payment_settlement_allocations_company_id_id')
    )
    op.create_index(op.f('ix_payment_settlement_allocations_company_id'), 'payment_settlement_allocations', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_settlement_allocations_open_item_id'), 'payment_settlement_allocations', ['open_item_id'], unique=False)
    op.create_index(op.f('ix_payment_settlement_allocations_payment_id'), 'payment_settlement_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_settlement_allocations_status'), 'payment_settlement_allocations', ['status'], unique=False)
    op.create_index('ix_payment_settlement_open_item_active', 'payment_settlement_allocations', ['company_id', 'open_item_id', 'id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_payment_settlement_payment_active', 'payment_settlement_allocations', ['company_id', 'payment_id', 'id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_payment_settlement_active_pair', 'payment_settlement_allocations', ['company_id', 'payment_id', 'open_item_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payment_settlement_active_pair', table_name='payment_settlement_allocations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_payment_settlement_payment_active', table_name='payment_settlement_allocations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_payment_settlement_open_item_active', table_name='payment_settlement_allocations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_payment_settlement_allocations_status'), table_name='payment_settlement_allocations')
    op.drop_index(op.f('ix_payment_settlement_allocations_payment_id'), table_name='payment_settlement_allocations')
    op.drop_index(op.f('ix_payment_settlement_allocations_open_item_id'), table_name='payment_settlement_allocations')
    op.drop_index(op.f('ix_payment_settlement_allocations_company_id'), table_name='payment_settlement_allocations')
    op.drop_table('payment_settlement_allocations')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_direction'), table_name='payments')
    op.drop_index(op.f('ix_payments_currency_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_counterparty_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_contract_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
