"""add payroll statutory foundation

Revision ID: 864b767fc1c7
Revises: 36e215ca4492
Create Date: 2026-10-03 10:18:40.772337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864b767fc1c7'
down_revision: Union[str, Sequence[str], None] = '36e215ca4492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_statutory_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component IN ('personal_income_tax', 'military_levy', 'unified_social_contribution')", name='ck_payroll_statutory_rates_component'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_payroll_statutory_rates_effective_range'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_payroll_statutory_rates_rate_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_payroll_statutory_rates_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_payroll_statutory_rates_created_by', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_statutory_rates_company_id_id')
    )
    op.create_index('ix_payroll_statutory_rates_company_component_effective', 'payroll_statutory_rates', ['company_id', 'component', 'effective_from'], unique=False)
    op.create_table('payroll_statutory_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employee_withholding_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('employer_contribution_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('calculated_by', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('currency_code = upper(currency_code) AND char_length(currency_code) = 3', name='ck_payroll_statutory_results_currency'),
    sa.CheckConstraint('employee_withholding_amount >= 0', name='ck_payroll_statutory_results_employee_withholding_nonnegative'),
    sa.CheckConstraint('employer_contribution_amount >= 0', name='ck_payroll_statutory_results_employer_contribution_nonnegative'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_payroll_statutory_results_gross_nonnegative'),
    sa.CheckConstraint('net_amount = gross_amount - employee_withholding_amount', name='ck_payroll_statutory_results_net_reconciliation'),
    sa.CheckConstraint('net_amount >= 0', name='ck_payroll_statutory_results_net_nonnegative'),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], name='fk_payroll_statutory_results_calculated_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_calculation_id'], ['payroll_calculations.company_id', 'payroll_calculations.id'], name='fk_payroll_statutory_results_company_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_statutory_results_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_calculation_id', name='uq_payroll_statutory_results_company_calculation')
    )
    op.create_index('ix_payroll_statutory_results_company_calculation', 'payroll_statutory_results', ['company_id', 'payroll_calculation_id'], unique=False)
    op.create_table('payroll_statutory_result_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_statutory_result_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('source_rate_id', sa.Integer(), nullable=False),
    sa.Column('rate_effective_from', sa.Date(), nullable=False),
    sa.Column('rate_effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component IN ('personal_income_tax', 'military_levy', 'unified_social_contribution')", name='ck_payroll_statutory_lines_component'),
    sa.CheckConstraint('amount >= 0', name='ck_payroll_statutory_lines_amount_nonnegative'),
    sa.CheckConstraint('base_amount >= 0', name='ck_payroll_statutory_lines_base_nonnegative'),
    sa.CheckConstraint('currency_code = upper(currency_code) AND char_length(currency_code) = 3', name='ck_payroll_statutory_lines_currency'),
    sa.CheckConstraint('line_no > 0', name='ck_payroll_statutory_lines_line_no_positive'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_payroll_statutory_lines_rate_range'),
    sa.CheckConstraint('rate_effective_to IS NULL OR rate_effective_to >= rate_effective_from', name='ck_payroll_statutory_lines_rate_effective_range'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_statutory_result_id'], ['payroll_statutory_results.company_id', 'payroll_statutory_results.id'], name='fk_payroll_statutory_lines_company_result', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'source_rate_id'], ['payroll_statutory_rates.company_id', 'payroll_statutory_rates.id'], name='fk_payroll_statutory_lines_company_rate', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'payroll_statutory_result_id', 'line_no', name='uq_payroll_statutory_lines_result_line_no')
    )
    op.create_index('ix_payroll_statutory_lines_company_result', 'payroll_statutory_result_lines', ['company_id', 'payroll_statutory_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payroll_statutory_lines_company_result', table_name='payroll_statutory_result_lines')
    op.drop_table('payroll_statutory_result_lines')
    op.drop_index('ix_payroll_statutory_results_company_calculation', table_name='payroll_statutory_results')
    op.drop_table('payroll_statutory_results')
    op.drop_index('ix_payroll_statutory_rates_company_component_effective', table_name='payroll_statutory_rates')
    op.drop_table('payroll_statutory_rates')
    # ### end Alembic commands ###
