"""add valuation amount to inventory cost entries

Revision ID: 88fb870cf382
Revises: 6ea25f081a83
Create Date: 2026-08-19 14:29:30.228770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fb870cf382'
down_revision: Union[str, Sequence[str], None] = '6ea25f081a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Add the column as nullable first because
    # existing inventory cost entries already exist.
    op.add_column(
        "inventory_cost_entries",
        sa.Column(
            "valuation_amount",
            sa.Numeric(
                precision=20,
                scale=8,
            ),
            nullable=True,
        ),
    )

    # 2. Backfill historical cost entries.
    op.execute(
        """
        UPDATE inventory_cost_entries
        SET valuation_amount =
            quantity * unit_cost
        WHERE valuation_amount IS NULL
        """
    )

    # 3. Make the column required after backfill.
    op.alter_column(
        "inventory_cost_entries",
        "valuation_amount",
        existing_type=sa.Numeric(
            precision=20,
            scale=8,
        ),
        nullable=False,
    )

    # 4. Protect against negative valuation amounts.
    op.create_check_constraint(
        "ck_inventory_cost_entry_valuation_amount_nonnegative",
        "inventory_cost_entries",
        "valuation_amount >= 0",
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_inventory_cost_entry_valuation_amount_nonnegative', 'inventory_cost_entries', type_='check')
    op.drop_column('inventory_cost_entries', 'valuation_amount')
    # ### end Alembic commands ###
