"""add payment accounting sources to journal entries

Revision ID: 9098606a8126
Revises: 84019bf78180
Create Date: 2026-08-29 17:06:04.344236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9098606a8126'
down_revision: Union[str, Sequence[str], None] = '84019bf78180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('journal_entries', sa.Column('payment_settlement_allocation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_journal_entries_payment_id'), 'journal_entries', ['payment_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_payment_settlement_allocation_id'), 'journal_entries', ['payment_settlement_allocation_id'], unique=False)
    op.create_index('uq_journal_entry_original_payment', 'journal_entries', ['payment_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NULL AND payment_id IS NOT NULL'))
    op.create_index('uq_journal_entry_original_payment_settlement_allocation', 'journal_entries', ['payment_settlement_allocation_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NULL AND payment_settlement_allocation_id IS NOT NULL'))
    op.create_foreign_key('fk_journal_entries_company_payment', 'journal_entries', 'payments', ['company_id', 'payment_id'], ['company_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_journal_entries_company_payment_settlement_allocation', 'journal_entries', 'payment_settlement_allocations', ['company_id', 'payment_settlement_allocation_id'], ['company_id', 'id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_journal_entries_at_most_one_business_source', 'journal_entries', '\n            (\n                document_id IS NULL\n                OR payment_id IS NULL\n            )\n            AND\n            (\n                document_id IS NULL\n                OR payment_settlement_allocation_id IS NULL\n            )\n            AND\n            (\n                payment_id IS NULL\n                OR payment_settlement_allocation_id IS NULL\n            )\n            ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_journal_entries_at_most_one_business_source', 'journal_entries', type_='check')
    op.drop_constraint('fk_journal_entries_company_payment_settlement_allocation', 'journal_entries', type_='foreignkey')
    op.drop_constraint('fk_journal_entries_company_payment', 'journal_entries', type_='foreignkey')
    op.drop_index('uq_journal_entry_original_payment_settlement_allocation', table_name='journal_entries', postgresql_where=sa.text('reversal_of_id IS NULL AND payment_settlement_allocation_id IS NOT NULL'))
    op.drop_index('uq_journal_entry_original_payment', table_name='journal_entries', postgresql_where=sa.text('reversal_of_id IS NULL AND payment_id IS NOT NULL'))
    op.drop_index(op.f('ix_journal_entries_payment_settlement_allocation_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_payment_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'payment_settlement_allocation_id')
    op.drop_column('journal_entries', 'payment_id')
    # ### end Alembic commands ###
