"""add time attendance foundation

Revision ID: 942689c3ff90
Revises: 7f3c91d42e10
Create Date: 2026-10-01 18:11:55.180927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942689c3ff90'
down_revision: Union[str, Sequence[str], None] = '7f3c91d42e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_work_schedules_code_nonempty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_work_schedules_name_nonempty'),
    sa.CheckConstraint('length(trim(timezone)) > 0', name='ck_work_schedules_timezone_nonempty'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_work_schedules_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_work_schedules_company_id_id')
    )
    op.create_index('ix_work_schedules_company_active', 'work_schedules', ['company_id', 'is_active'], unique=False)
    op.create_table('work_schedule_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('work_schedule_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_working_day = true AND start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time) OR (is_working_day = false AND start_time IS NULL AND end_time IS NULL)', name='ck_work_schedule_days_working_interval'),
    sa.CheckConstraint('break_minutes >= 0', name='ck_work_schedule_days_break_nonnegative'),
    sa.CheckConstraint('weekday >= 1 AND weekday <= 7', name='ck_work_schedule_days_weekday'),
    sa.ForeignKeyConstraint(['company_id', 'work_schedule_id'], ['work_schedules.company_id', 'work_schedules.id'], name='fk_work_schedule_days_company_schedule', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_work_schedule_days_company_id_id'),
    sa.UniqueConstraint('company_id', 'work_schedule_id', 'weekday', name='uq_work_schedule_days_company_schedule_weekday')
    )
    op.create_index('ix_work_schedule_days_company_schedule', 'work_schedule_days', ['company_id', 'work_schedule_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('break_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('worked_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'present' AND actual_start_at IS NOT NULL AND actual_end_at IS NOT NULL) OR (status <> 'present' AND actual_start_at IS NULL AND actual_end_at IS NULL AND worked_minutes = 0)", name='ck_attendance_records_status_time'),
    sa.CheckConstraint("source IN ('manual','import','system')", name='ck_attendance_records_source'),
    sa.CheckConstraint("status IN ('present','absent','leave','sick','holiday','day_off')", name='ck_attendance_records_status'),
    sa.CheckConstraint('actual_end_at IS NULL OR actual_start_at IS NULL OR actual_end_at >= actual_start_at', name='ck_attendance_records_actual_range'),
    sa.CheckConstraint('break_minutes >= 0', name='ck_attendance_records_break_nonnegative'),
    sa.CheckConstraint('worked_minutes >= 0', name='ck_attendance_records_worked_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_attendance_records_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employment_contract_id', 'work_date', name='uq_attendance_records_company_contract_date'),
    sa.UniqueConstraint('company_id', 'id', name='uq_attendance_records_company_id_id')
    )
    op.create_index('ix_attendance_records_company_contract_date', 'attendance_records', ['company_id', 'employment_contract_id', 'work_date'], unique=False)
    op.create_index('ix_attendance_records_company_status', 'attendance_records', ['company_id', 'status'], unique=False)
    op.create_index('ix_attendance_records_company_work_date', 'attendance_records', ['company_id', 'work_date'], unique=False)
    op.create_table('employment_schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('work_schedule_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_employment_schedule_assignments_date_range'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_employment_schedule_assignments_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'work_schedule_id'], ['work_schedules.company_id', 'work_schedules.id'], name='fk_employment_schedule_assignments_company_schedule', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_employment_schedule_assignments_company_id_id')
    )
    op.create_index('ix_employment_schedule_assignments_company_contract', 'employment_schedule_assignments', ['company_id', 'employment_contract_id', 'effective_from'], unique=False)
    op.create_index('ix_employment_schedule_assignments_company_schedule', 'employment_schedule_assignments', ['company_id', 'work_schedule_id'], unique=False)
    op.drop_constraint(
        'ck_hr_changes_entity_type',
        'hr_changes',
        type_='check',
    )
    op.create_check_constraint(
        'ck_hr_changes_entity_type',
        'hr_changes',
        "entity_type IN ("
        "'employee','department','position',"
        "'employment_contract','salary_rate',"
        "'work_schedule','employment_schedule_assignment',"
        "'attendance_record'"
        ")",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Restore the pre-13.4 HR history entity contract first.
    op.drop_constraint(
        'ck_hr_changes_entity_type',
        'hr_changes',
        type_='check',
    )
    op.create_check_constraint(
        'ck_hr_changes_entity_type',
        'hr_changes',
        "entity_type IN ("
        "'employee','department','position',"
        "'employment_contract','salary_rate'"
        ")",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employment_schedule_assignments_company_schedule', table_name='employment_schedule_assignments')
    op.drop_index('ix_employment_schedule_assignments_company_contract', table_name='employment_schedule_assignments')
    op.drop_table('employment_schedule_assignments')
    op.drop_index('ix_attendance_records_company_work_date', table_name='attendance_records')
    op.drop_index('ix_attendance_records_company_status', table_name='attendance_records')
    op.drop_index('ix_attendance_records_company_contract_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_work_schedule_days_company_schedule', table_name='work_schedule_days')
    op.drop_table('work_schedule_days')
    op.drop_index('ix_work_schedules_company_active', table_name='work_schedules')
    op.drop_table('work_schedules')
    # ### end Alembic commands ###
