"""add unique original journal entry per document

Revision ID: 9ac7557673fb
Revises: dac3ce15642a
Create Date: 2026-08-18 13:21:40.372675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac7557673fb'
down_revision: Union[str, Sequence[str], None] = 'dac3ce15642a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_journal_entry_original_document', 'journal_entries', ['document_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NULL AND document_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_journal_entry_original_document', table_name='journal_entries', postgresql_where=sa.text('reversal_of_id IS NULL AND document_id IS NOT NULL'))
    # ### end Alembic commands ###
