"""allow tax recognition source adjustments

Revision ID: a09dad8c4dea
Revises: ea89bcd571ae
Create Date: 2026-08-30 23:47:06.765828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09dad8c4dea'
down_revision: Union[str, Sequence[str], None] = 'ea89bcd571ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_tax_recognition_events_original_fulfillment_source'), table_name='tax_recognition_events', postgresql_where='((reversal_of_id IS NULL) AND (invoice_fulfillment_allocation_id IS NOT NULL))')
    op.drop_index(op.f('uq_tax_recognition_events_original_settlement_source'), table_name='tax_recognition_events', postgresql_where='((reversal_of_id IS NULL) AND (payment_settlement_allocation_id IS NOT NULL))')
    op.create_index('ix_tax_recognition_events_fulfillment_source', 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'invoice_fulfillment_allocation_id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL AND invoice_fulfillment_allocation_id IS NOT NULL'))
    op.create_index('ix_tax_recognition_events_settlement_source', 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'payment_settlement_allocation_id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL AND payment_settlement_allocation_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tax_recognition_events_settlement_source', table_name='tax_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL AND payment_settlement_allocation_id IS NOT NULL'))
    op.drop_index('ix_tax_recognition_events_fulfillment_source', table_name='tax_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL AND invoice_fulfillment_allocation_id IS NOT NULL'))
    op.create_index(op.f('uq_tax_recognition_events_original_settlement_source'), 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'payment_settlement_allocation_id'], unique=True, postgresql_where='((reversal_of_id IS NULL) AND (payment_settlement_allocation_id IS NOT NULL))')
    op.create_index(op.f('uq_tax_recognition_events_original_fulfillment_source'), 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'invoice_fulfillment_allocation_id'], unique=True, postgresql_where='((reversal_of_id IS NULL) AND (invoice_fulfillment_allocation_id IS NOT NULL))')
    # ### end Alembic commands ###
