"""add fixed asset revaluation impairment lifecycle

Revision ID: a33efad6aeaa
Revises: b0ea2ffa2b41
Create Date: 2026-09-28 15:47:05.074494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33efad6aeaa'
down_revision: Union[str, Sequence[str], None] = 'b0ea2ffa2b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_revaluation_impairments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('revaluation', 'impairment', name='fixed_asset_revaluation_impairment_type_enum', native_enum=False, length=20), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('carrying_amount_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('carrying_amount_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('original_cost_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('original_cost_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterpart_account_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_fari2_amount_positive'),
    sa.CheckConstraint('carrying_amount_after >= 0', name='ck_fari2_carrying_after_nonnegative'),
    sa.CheckConstraint('carrying_amount_before >= 0', name='ck_fari2_carrying_before_nonnegative'),
    sa.CheckConstraint('original_cost_after >= 0', name='ck_fari2_original_after_nonnegative'),
    sa.CheckConstraint('original_cost_before >= 0', name='ck_fari2_original_before_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'counterpart_account_id'], ['accounts.company_id', 'accounts.id'], name='fk_fari2_company_counterpart_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'fixed_asset_id'], ['fixed_assets.company_id', 'fixed_assets.id'], name='fk_fari2_company_asset', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id'], ['fixed_asset_revaluation_impairments.company_id', 'fixed_asset_revaluation_impairments.id'], name='fk_fari2_company_reversal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_fari2_company_id_id'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_fari2_company_request_key')
    )
    op.create_index('ix_fari2_company_asset', 'fixed_asset_revaluation_impairments', ['company_id', 'fixed_asset_id'], unique=False)
    op.create_index(op.f('ix_fixed_asset_revaluation_impairments_company_id'), 'fixed_asset_revaluation_impairments', ['company_id'], unique=False)
    op.create_index(op.f('ix_fixed_asset_revaluation_impairments_journal_entry_id'), 'fixed_asset_revaluation_impairments', ['journal_entry_id'], unique=False)
    op.create_index('uq_fari2_reversal_of', 'fixed_asset_revaluation_impairments', ['reversal_of_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NOT NULL'))
    op.add_column('journal_entries', sa.Column('fixed_asset_revaluation_impairment_id', sa.Integer(), nullable=True))
    op.create_index('ix_je_fixed_asset_revaluation_impairment', 'journal_entries', ['fixed_asset_revaluation_impairment_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_fixed_asset_revaluation_impairment_id'), 'journal_entries', ['fixed_asset_revaluation_impairment_id'], unique=False)
    op.create_index('uq_je_fixed_asset_revaluation_impairment_original', 'journal_entries', ['fixed_asset_revaluation_impairment_id'], unique=True, postgresql_where=sa.text('fixed_asset_revaluation_impairment_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.create_foreign_key('fk_je_company_fixed_asset_revaluation_impairment', 'journal_entries', 'fixed_asset_revaluation_impairments', ['company_id', 'fixed_asset_revaluation_impairment_id'], ['company_id', 'id'], ondelete='RESTRICT', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_je_company_fixed_asset_revaluation_impairment', 'journal_entries', type_='foreignkey')
    op.drop_index('uq_je_fixed_asset_revaluation_impairment_original', table_name='journal_entries', postgresql_where=sa.text('fixed_asset_revaluation_impairment_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.drop_index(op.f('ix_journal_entries_fixed_asset_revaluation_impairment_id'), table_name='journal_entries')
    op.drop_index('ix_je_fixed_asset_revaluation_impairment', table_name='journal_entries')
    op.drop_column('journal_entries', 'fixed_asset_revaluation_impairment_id')
    op.drop_index('uq_fari2_reversal_of', table_name='fixed_asset_revaluation_impairments', postgresql_where=sa.text('reversal_of_id IS NOT NULL'))
    op.drop_index(op.f('ix_fixed_asset_revaluation_impairments_journal_entry_id'), table_name='fixed_asset_revaluation_impairments')
    op.drop_index(op.f('ix_fixed_asset_revaluation_impairments_company_id'), table_name='fixed_asset_revaluation_impairments')
    op.drop_index('ix_fari2_company_asset', table_name='fixed_asset_revaluation_impairments')
    op.drop_table('fixed_asset_revaluation_impairments')
    # ### end Alembic commands ###
