"""add attested input VAT credit claims

Revision ID: a4cbd7f9b268
Revises: f3bac6e8a157
Create Date: 2026-09-16 17:42:25.263884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4cbd7f9b268'
down_revision: Union[str, Sequence[str], None] = 'f3bac6e8a157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_vat_credit_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tax_calculation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('reversal_evidence_id', sa.Integer(), nullable=True),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('claim_period', sa.Date(), nullable=False),
    sa.Column('attestation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM claim_period) = 1', name='ck_ivcc_month'),
    sa.CheckConstraint('reversal_evidence_id IS NULL OR reversal_evidence_id <> evidence_id', name='ck_ivcc_distinct_reversal'),
    sa.CheckConstraint('length(trim(request_key)) > 0 AND length(policy_version) > 0', name='ck_ivcc_identifiers'),
    sa.ForeignKeyConstraint(['company_id', 'evidence_id', 'tax_calculation_id'], ['tax_credit_evidence.company_id', 'tax_credit_evidence.id', 'tax_credit_evidence.tax_calculation_id'], name='fk_ivcc_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_evidence_id', 'tax_calculation_id'], ['tax_credit_evidence.company_id', 'tax_credit_evidence.id', 'tax_credit_evidence.tax_calculation_id'], name='fk_ivcc_reversal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_ivcc_request'),
    sa.UniqueConstraint('evidence_id', name='uq_ivcc_evidence'),
    sa.UniqueConstraint('reversal_evidence_id', name='uq_ivcc_reversal')
    )
    op.create_index('ix_ivcc_company_calculation', 'input_vat_credit_claims', ['company_id', 'tax_calculation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('input_vat_credit_claims')
    # ### end Alembic commands ###
