"""add payroll disbursement foundation

Revision ID: ae1b3f877577
Revises: 080a2cca7057
Create Date: 2026-10-03 16:43:20.459240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1b3f877577'
down_revision: Union[str, Sequence[str], None] = '080a2cca7057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('employee_iban_snapshot', sa.String(length=34), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'bank_account_id'], ['bank_accounts.company_id', 'bank_accounts.id'], name='fk_payroll_disbursements_company_bank_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employee_id'], ['employees.company_id', 'employees.id'], name='fk_payroll_disbursements_company_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_calculation_id'], ['payroll_calculations.company_id', 'payroll_calculations.id'], name='fk_payroll_disbursements_company_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_disbursements_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_calculation_id', name='uq_payroll_disbursements_company_calculation')
    )
    op.create_index(op.f('ix_payroll_disbursements_company_id'), 'payroll_disbursements', ['company_id'], unique=False)
    op.create_index('ix_payroll_disbursements_company_payment_date', 'payroll_disbursements', ['company_id', 'payment_date'], unique=False)
    op.add_column('journal_entries', sa.Column('payroll_disbursement_id', sa.Integer(), nullable=True))
    op.create_index('ix_je_payroll_disbursement', 'journal_entries', ['payroll_disbursement_id'], unique=False)
    op.create_index('uq_je_original_payroll_disbursement', 'journal_entries', ['company_id', 'payroll_disbursement_id'], unique=True, postgresql_where=sa.text('payroll_disbursement_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.create_foreign_key('fk_je_company_payroll_disbursement', 'journal_entries', 'payroll_disbursements', ['company_id', 'payroll_disbursement_id'], ['company_id', 'id'], ondelete='RESTRICT', use_alter=True)
    op.drop_constraint(
        'ck_je_payroll_calculation_exclusive',
        'journal_entries',
        type_='check',
    )
    op.create_check_constraint(
        'ck_je_payroll_calculation_exclusive',
        'journal_entries',
        'payroll_calculation_id IS NULL OR num_nonnulls(payroll_disbursement_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0',
    )
    op.create_check_constraint('ck_je_payroll_disbursement_exclusive', 'journal_entries', 'payroll_disbursement_id IS NULL OR num_nonnulls(payroll_calculation_id,customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_je_payroll_disbursement_exclusive', 'journal_entries', type_='check')
    op.drop_constraint(
        'ck_je_payroll_calculation_exclusive',
        'journal_entries',
        type_='check',
    )
    op.create_check_constraint(
        'ck_je_payroll_calculation_exclusive',
        'journal_entries',
        'payroll_calculation_id IS NULL OR num_nonnulls(customer_advance_clearing_event_id,document_id,fixed_asset_commissioning_id,input_vat_fulfillment_bridge_event_id,opening_balance_id,payment_id,payment_settlement_allocation_id,purchase_return_input_vat_credit_correction_event_id,purchase_return_recognition_event_id,purchase_return_vat_adjustment_event_id,purchase_value_correction_fifo_impact_event_id,purchase_value_correction_input_vat_credit_correction_event_id,purchase_value_correction_ma_replay_event_id,purchase_value_correction_vat_adjustment_event_id,sales_recognition_event_id,sales_return_cost_restoration_event_id,sales_return_recognition_event_id,supplier_advance_clearing_event_id,tax_invoice_correction_line_id,tax_recognition_event_id,vat_advance_bridge_event_id,year_end_closing_id) = 0',
    )

    op.drop_constraint('fk_je_company_payroll_disbursement', 'journal_entries', type_='foreignkey')
    op.drop_index('uq_je_original_payroll_disbursement', table_name='journal_entries', postgresql_where=sa.text('payroll_disbursement_id IS NOT NULL AND reversal_of_id IS NULL'))
    op.drop_index('ix_je_payroll_disbursement', table_name='journal_entries')
    op.drop_column('journal_entries', 'payroll_disbursement_id')
    op.drop_index('ix_payroll_disbursements_company_payment_date', table_name='payroll_disbursements')
    op.drop_index(op.f('ix_payroll_disbursements_company_id'), table_name='payroll_disbursements')
    op.drop_table('payroll_disbursements')
    # ### end Alembic commands ###
