"""add payroll advance foundation

Revision ID: b082b6582130
Revises: 13d4a7b8c008
Create Date: 2026-10-05 11:30:45.575430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b082b6582130'
down_revision: Union[str, Sequence[str], None] = '13d4a7b8c008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('advance_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('calculation_base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('minimum_due_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('advance_percentage > 0 AND advance_percentage <= 100', name='ck_payroll_advances_percentage'),
    sa.CheckConstraint('calculated_amount > 0', name='ck_payroll_advances_calculated_amount_positive'),
    sa.CheckConstraint('currency_code = upper(currency_code) AND char_length(currency_code) = 3', name='ck_payroll_advances_currency'),
    sa.CheckConstraint('minimum_due_amount >= 0', name='ck_payroll_advances_minimum_due_nonnegative'),
    sa.CheckConstraint('paid_amount <= calculated_amount', name='ck_payroll_advances_paid_lte_calculated'),
    sa.CheckConstraint('paid_amount > 0', name='ck_payroll_advances_paid_amount_positive'),
    sa.CheckConstraint('paid_amount >= minimum_due_amount', name='ck_payroll_advances_paid_gte_minimum'),
    sa.ForeignKeyConstraint(['company_id', 'bank_account_id'], ['bank_accounts.company_id', 'bank_accounts.id'], name='fk_payroll_advances_company_bank', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_advances_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_period_id'], ['payroll_periods.company_id', 'payroll_periods.id'], name='fk_payroll_advances_company_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_advances_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_period_id', 'employment_contract_id', name='uq_payroll_advances_company_period_contract')
    )
    op.create_index('ix_payroll_advances_company_payment_date', 'payroll_advances', ['company_id', 'payment_date'], unique=False)

    op.add_column(
        'journal_entries',
        sa.Column(
            'payroll_advance_id',
            sa.Integer(),
            nullable=True,
        ),
    )
    op.create_index(
        'ix_je_payroll_advance',
        'journal_entries',
        ['payroll_advance_id'],
        unique=False,
    )
    op.create_index(
        'uq_je_original_payroll_advance',
        'journal_entries',
        ['company_id', 'payroll_advance_id'],
        unique=True,
        postgresql_where=sa.text(
            'payroll_advance_id IS NOT NULL '
            'AND reversal_of_id IS NULL'
        ),
    )
    op.create_foreign_key(
        'fk_je_company_payroll_advance',
        'journal_entries',
        'payroll_advances',
        ['company_id', 'payroll_advance_id'],
        ['company_id', 'id'],
        ondelete='RESTRICT',
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM payroll_advances) THEN
            RAISE EXCEPTION 'Payroll advance history must be preserved';
        END IF;
    END $$""")
    op.drop_constraint('fk_je_company_payroll_advance', 'journal_entries', type_='foreignkey')
    op.drop_index('uq_je_original_payroll_advance', table_name='journal_entries')
    op.drop_index('ix_je_payroll_advance', table_name='journal_entries')
    op.drop_column('journal_entries', 'payroll_advance_id')
    op.drop_index('ix_payroll_advances_company_payment_date', table_name='payroll_advances')
    op.drop_table('payroll_advances')
    # ### end Alembic commands ###
