"""add sales recognition events

Revision ID: b664d727d446
Revises: c3f5a71b9d20
Create Date: 2026-09-01 17:36:03.057336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b664d727d446'
down_revision: Union[str, Sequence[str], None] = 'c3f5a71b9d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_recognition_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('invoice_fulfillment_allocation_id', sa.Integer(), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=False),
    sa.Column('recognized_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('recognized_gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recognized_tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_sales_recognition_events_currency_code_length'),
    sa.CheckConstraint('recognized_gross_amount > 0', name='ck_sales_recognition_events_gross_amount_positive'),
    sa.CheckConstraint('recognized_quantity > 0', name='ck_sales_recognition_events_quantity_positive'),
    sa.CheckConstraint('recognized_tax_amount <= recognized_gross_amount', name='ck_sales_recognition_events_tax_not_above_gross'),
    sa.CheckConstraint('recognized_tax_amount >= 0', name='ck_sales_recognition_events_tax_amount_nonnegative'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_of_id <> id', name='ck_sales_recognition_events_not_self_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'invoice_fulfillment_allocation_id'], ['invoice_fulfillment_allocations.company_id', 'invoice_fulfillment_allocations.id'], name='fk_sales_recognition_events_company_fulfillment_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id', 'invoice_fulfillment_allocation_id'], ['sales_recognition_events.company_id', 'sales_recognition_events.id', 'sales_recognition_events.invoice_fulfillment_allocation_id'], name='fk_sales_recognition_events_company_reversal_of_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', 'invoice_fulfillment_allocation_id', name='uq_sales_recognition_events_company_id_id_fulfillment_source'),
    sa.UniqueConstraint('company_id', 'id', name='uq_sales_recognition_events_company_id_id'),
    sa.UniqueConstraint('reversal_of_id', name='uq_sales_recognition_events_reversal_of')
    )
    op.create_index(op.f('ix_sales_recognition_events_company_id'), 'sales_recognition_events', ['company_id'], unique=False)
    op.create_index('ix_sales_recognition_events_fulfillment_source_original', 'sales_recognition_events', ['company_id', 'invoice_fulfillment_allocation_id', 'id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.create_index(op.f('ix_sales_recognition_events_invoice_fulfillment_allocation_id'), 'sales_recognition_events', ['invoice_fulfillment_allocation_id'], unique=False)
    op.create_index(op.f('ix_sales_recognition_events_recognition_date'), 'sales_recognition_events', ['recognition_date'], unique=False)
    op.create_index(op.f('ix_sales_recognition_events_reversal_of_id'), 'sales_recognition_events', ['reversal_of_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_recognition_events_reversal_of_id'), table_name='sales_recognition_events')
    op.drop_index(op.f('ix_sales_recognition_events_recognition_date'), table_name='sales_recognition_events')
    op.drop_index(op.f('ix_sales_recognition_events_invoice_fulfillment_allocation_id'), table_name='sales_recognition_events')
    op.drop_index('ix_sales_recognition_events_fulfillment_source_original', table_name='sales_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.drop_index(op.f('ix_sales_recognition_events_company_id'), table_name='sales_recognition_events')
    op.drop_table('sales_recognition_events')
    # ### end Alembic commands ###
