"""add tax credit evidence effective date

Revision ID: b8cad71d9a7e
Revises: 147c44d3f4f1
Create Date: 2026-09-02 17:48:24.933265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cad71d9a7e'
down_revision: Union[str, Sequence[str], None] = '147c44d3f4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_credit_evidence', sa.Column('effective_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_tax_credit_evidence_effective_date'), 'tax_credit_evidence', ['effective_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_credit_evidence_effective_date'), table_name='tax_credit_evidence')
    op.drop_column('tax_credit_evidence', 'effective_date')
    # ### end Alembic commands ###
