"""add payroll calculation foundation

Revision ID: ba5bf40a8bc7
Revises: 3fa9354d7a92
Create Date: 2026-10-02 18:04:10.464450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5bf40a8bc7'
down_revision: Union[str, Sequence[str], None] = '3fa9354d7a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('payroll_input_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('calculated', name='payroll_calculation_status', native_enum=False), server_default='calculated', nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('calculated_by', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('calculated')", name='ck_payroll_calculations_status'),
    sa.CheckConstraint('currency_code = upper(currency_code) AND char_length(currency_code) = 3', name='ck_payroll_calculations_currency'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_payroll_calculations_gross_nonnegative'),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_calculations_company_contract', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_input_id'], ['payroll_inputs.company_id', 'payroll_inputs.id'], name='fk_payroll_calculations_company_input', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_period_id'], ['payroll_periods.company_id', 'payroll_periods.id'], name='fk_payroll_calculations_company_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_calculations_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_period_id', 'employment_contract_id', name='uq_payroll_calculations_company_period_contract')
    )
    op.create_index('ix_payroll_calculations_company_contract', 'payroll_calculations', ['company_id', 'employment_contract_id'], unique=False)
    op.create_index('ix_payroll_calculations_company_period', 'payroll_calculations', ['company_id', 'payroll_period_id'], unique=False)
    op.create_table('payroll_calculation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('salary_rate_type', sa.String(length=16), nullable=True),
    sa.Column('source_salary_rate_id', sa.Integer(), nullable=True),
    sa.Column('source_effective_from', sa.Date(), nullable=True),
    sa.Column('source_effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("line_type IN ('salary','manual_adjustment')", name='ck_payroll_calculation_lines_type'),
    sa.CheckConstraint("(line_type = 'salary' AND amount >= 0) OR line_type = 'manual_adjustment'", name='ck_payroll_calculation_lines_amount_by_type'),
    sa.CheckConstraint('currency_code = upper(currency_code) AND char_length(currency_code) = 3', name='ck_payroll_calculation_lines_currency'),
    sa.CheckConstraint('line_no > 0', name='ck_payroll_calculation_lines_line_no_positive'),
    sa.CheckConstraint('quantity >= 0', name='ck_payroll_calculation_lines_quantity_nonnegative'),
    sa.CheckConstraint('rate >= 0', name='ck_payroll_calculation_lines_rate_nonnegative'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_calculation_id'], ['payroll_calculations.company_id', 'payroll_calculations.id'], name='fk_payroll_calculation_lines_company_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(
        ['company_id', 'source_salary_rate_id'],
        ['employee_salary_rates.company_id', 'employee_salary_rates.id'],
        name='fk_payroll_calculation_lines_company_salary_rate',
        ondelete='RESTRICT'
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_calculation_lines_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_calculation_id', 'line_no', name='uq_payroll_calculation_lines_company_calculation_line_no')
    )
    op.create_index('ix_payroll_calculation_lines_company_calculation', 'payroll_calculation_lines', ['company_id', 'payroll_calculation_id', 'line_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payroll_calculation_lines_company_calculation', table_name='payroll_calculation_lines')
    op.drop_table('payroll_calculation_lines')
    op.drop_index('ix_payroll_calculations_company_period', table_name='payroll_calculations')
    op.drop_index('ix_payroll_calculations_company_contract', table_name='payroll_calculations')
    op.drop_table('payroll_calculations')
    # ### end Alembic commands ###
