"""add payroll regulatory reporting foundation

Revision ID: bb0425a7fbd6
Revises: e69c41b1db42
Create Date: 2026-10-07 14:21:55.095350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0425a7fbd6'
down_revision: Union[str, Sequence[str], None] = 'e69c41b1db42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_regulatory_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('report_kind', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'draft'\n                AND generated_at IS NULL\n                AND generated_by IS NULL\n            )\n            OR\n            (\n                status = 'generated'\n                AND generated_at IS NOT NULL\n                AND generated_by IS NOT NULL\n            )\n            ", name='ck_payroll_regulatory_reports_generation_metadata'),
    sa.CheckConstraint("report_kind IN ('d1', '4df', 'd5', 'd6')", name='ck_payroll_regulatory_reports_kind'),
    sa.CheckConstraint("status IN ('draft', 'generated')", name='ck_payroll_regulatory_reports_status'),
    sa.CheckConstraint('revision > 0', name='ck_payroll_regulatory_reports_revision_positive'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_period_id'], ['payroll_periods.company_id', 'payroll_periods.id'], name='fk_payroll_regulatory_reports_company_period', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_regulatory_reports_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_period_id', 'report_kind', 'revision', name='uq_payroll_regulatory_reports_period_kind_revision')
    )
    op.create_index('ix_payroll_regulatory_reports_company_kind_status', 'payroll_regulatory_reports', ['company_id', 'report_kind', 'status'], unique=False)
    op.create_index('ix_payroll_regulatory_reports_company_period', 'payroll_regulatory_reports', ['company_id', 'payroll_period_id'], unique=False)
    op.create_table('payroll_regulatory_report_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_regulatory_report_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employment_contract_id', sa.Integer(), nullable=True),
    sa.Column('payroll_calculation_id', sa.Integer(), nullable=True),
    sa.Column('row_code', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('employee_id IS NOT NULL OR employment_contract_id IS NOT NULL', name='ck_payroll_regulatory_report_rows_source_present'),
    sa.CheckConstraint('row_no > 0', name='ck_payroll_regulatory_report_rows_row_no_positive'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_regulatory_report_id'], ['payroll_regulatory_reports.company_id', 'payroll_regulatory_reports.id'], name='fk_payroll_regulatory_report_rows_company_report', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_regulatory_report_rows_company_id_id'),
    sa.UniqueConstraint('company_id', 'payroll_regulatory_report_id', 'row_no', name='uq_payroll_regulatory_report_rows_report_row_no')
    )
    op.create_index('ix_payroll_regulatory_report_rows_company_employee', 'payroll_regulatory_report_rows', ['company_id', 'employee_id'], unique=False)
    op.create_index('ix_payroll_regulatory_report_rows_company_report', 'payroll_regulatory_report_rows', ['company_id', 'payroll_regulatory_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payroll_regulatory_report_rows_company_report', table_name='payroll_regulatory_report_rows')
    op.drop_index('ix_payroll_regulatory_report_rows_company_employee', table_name='payroll_regulatory_report_rows')
    op.drop_table('payroll_regulatory_report_rows')
    op.drop_index('ix_payroll_regulatory_reports_company_period', table_name='payroll_regulatory_reports')
    op.drop_index('ix_payroll_regulatory_reports_company_kind_status', table_name='payroll_regulatory_reports')
    op.drop_table('payroll_regulatory_reports')
    # ### end Alembic commands ###
