"""add bank statements

Revision ID: c8d2e5f4a701
Revises: b7a1c4e2d903
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "c8d2e5f4a701"
down_revision: str | None = "b7a1c4e2d903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "bank_statements",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "bank_account_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "external_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "statement_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "period_start",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "period_end",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "source_type",
            sa.String(length=50),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "source_reference",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(external_id)) > 0",
            name=(
                "ck_bank_statements_"
                "external_id_nonempty"
            ),
        ),
        sa.CheckConstraint(
            (
                "period_end IS NULL "
                "OR period_start IS NULL "
                "OR period_end >= period_start"
            ),
            name="ck_bank_statements_period_order",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_bank_statements_company",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_bank_statements_created_by",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "bank_account_id",
            ],
            [
                "bank_accounts.company_id",
                "bank_accounts.id",
            ],
            name=(
                "fk_bank_statements_"
                "company_bank_account"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_bank_statements",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name=(
                "uq_bank_statements_company_id_id"
            ),
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "bank_account_id",
            name=(
                "uq_bank_statements_"
                "company_id_id_bank_account_id"
            ),
        ),
        sa.UniqueConstraint(
            "company_id",
            "bank_account_id",
            "external_id",
            name=(
                "uq_bank_statements_"
                "company_account_external"
            ),
        ),
    )

    op.create_index(
        "ix_bank_statements_company_id",
        "bank_statements",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statements_bank_account_id",
        "bank_statements",
        ["bank_account_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statements_statement_date",
        "bank_statements",
        ["statement_date"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statements_created_by",
        "bank_statements",
        ["created_by"],
        unique=False,
    )

    op.create_table(
        "bank_statement_lines",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "bank_statement_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "bank_account_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "external_line_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "transaction_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "value_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "currency_code",
            sa.String(length=3),
            nullable=False,
        ),
        sa.Column(
            "counterparty_name",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "counterparty_account",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "payment_reference",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.String(length=2000),
            nullable=True,
        ),
        sa.Column(
            "raw_payload",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(external_line_id)) > 0",
            name=(
                "ck_bank_statement_lines_"
                "external_line_id_nonempty"
            ),
        ),
        sa.CheckConstraint(
            "amount <> 0",
            name=(
                "ck_bank_statement_lines_"
                "amount_nonzero"
            ),
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3",
            name=(
                "ck_bank_statement_lines_"
                "currency_code_length"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "bank_statement_id",
                "bank_account_id",
            ],
            [
                "bank_statements.company_id",
                "bank_statements.id",
                "bank_statements.bank_account_id",
            ],
            name=(
                "fk_bank_statement_lines_"
                "statement_identity"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_bank_statement_lines",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name=(
                "uq_bank_statement_lines_"
                "company_id_id"
            ),
        ),
        sa.UniqueConstraint(
            "company_id",
            "bank_statement_id",
            "external_line_id",
            name=(
                "uq_bank_statement_lines_"
                "statement_external_line"
            ),
        ),
    )

    op.create_index(
        "ix_bank_statement_lines_company_id",
        "bank_statement_lines",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statement_lines_bank_statement_id",
        "bank_statement_lines",
        ["bank_statement_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statement_lines_bank_account_id",
        "bank_statement_lines",
        ["bank_account_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statement_lines_transaction_date",
        "bank_statement_lines",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statement_lines_currency_code",
        "bank_statement_lines",
        ["currency_code"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_bank_statement_lines_currency_code",
        table_name="bank_statement_lines",
    )
    op.drop_index(
        "ix_bank_statement_lines_transaction_date",
        table_name="bank_statement_lines",
    )
    op.drop_index(
        "ix_bank_statement_lines_bank_account_id",
        table_name="bank_statement_lines",
    )
    op.drop_index(
        "ix_bank_statement_lines_bank_statement_id",
        table_name="bank_statement_lines",
    )
    op.drop_index(
        "ix_bank_statement_lines_company_id",
        table_name="bank_statement_lines",
    )
    op.drop_table("bank_statement_lines")

    op.drop_index(
        "ix_bank_statements_created_by",
        table_name="bank_statements",
    )
    op.drop_index(
        "ix_bank_statements_statement_date",
        table_name="bank_statements",
    )
    op.drop_index(
        "ix_bank_statements_bank_account_id",
        table_name="bank_statements",
    )
    op.drop_index(
        "ix_bank_statements_company_id",
        table_name="bank_statements",
    )
    op.drop_table("bank_statements")
