"""add payroll deduction instruction foundation

Revision ID: d134d84efd5f
Revises: 83d21036fabe
Create Date: 2026-10-06 20:22:27.821488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd134d84efd5f'
down_revision: Union[str, Sequence[str], None] = '83d21036fabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_deduction_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_contract_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                method = 'fixed'\n                AND fixed_amount IS NOT NULL\n                AND fixed_amount > 0\n                AND percentage IS NULL\n            )\n            OR\n            (\n                method = 'percentage'\n                AND percentage IS NOT NULL\n                AND percentage > 0\n                AND percentage <= 100\n                AND fixed_amount IS NULL\n            )\n            ", name='ck_payroll_deduction_instruction_value'),
    sa.CheckConstraint("method IN ('fixed', 'percentage')", name='ck_payroll_deduction_instruction_method'),
    sa.CheckConstraint('char_length(trim(deduction_type)) > 0', name='ck_payroll_deduction_instruction_type'),
    sa.CheckConstraint('char_length(trim(request_key)) > 0', name='ck_payroll_deduction_instruction_request_key'),
    sa.CheckConstraint('currency_code = upper(currency_code) AND char_length(currency_code) = 3', name='ck_payroll_deduction_instruction_currency'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_payroll_deduction_instruction_dates'),
    sa.CheckConstraint('priority >= 0', name='ck_payroll_deduction_instruction_priority'),
    sa.ForeignKeyConstraint(['company_id', 'employment_contract_id'], ['employment_contracts.company_id', 'employment_contracts.id'], name='fk_payroll_deduction_instruction_contract', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employment_contract_id', 'request_key', name='uq_payroll_deduction_instructions_request'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_deduction_instructions_company_id_id')
    )
    op.create_index('ix_payroll_deduction_instruction_company_priority', 'payroll_deduction_instructions', ['company_id', 'priority', 'id'], unique=False)
    op.create_index('ix_payroll_deduction_instruction_contract_dates', 'payroll_deduction_instructions', ['company_id', 'employment_contract_id', 'effective_from', 'effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payroll_deduction_instruction_contract_dates', table_name='payroll_deduction_instructions')
    op.drop_index('ix_payroll_deduction_instruction_company_priority', table_name='payroll_deduction_instructions')
    op.drop_table('payroll_deduction_instructions')
    # ### end Alembic commands ###
