"""add sales return cost restoration events

Revision ID: d4f7a9b2c601
Revises: c8e5d2a7f419
"""

from typing import (
    Sequence,
    Union,
)

from alembic import op
import sqlalchemy as sa


revision: str = "d4f7a9b2c601"

down_revision: Union[
    str,
    Sequence[str],
    None,
] = "c8e5d2a7f419"

branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None

depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    op.create_table(
        "sales_return_cost_restoration_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "trade_return_event_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "inventory_cost_entry_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "restoration_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "valuation_method",
            sa.String(
                length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "restored_quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "restored_valuation_amount",
            sa.Numeric(
                precision=24,
                scale=8,
            ),
            nullable=False,
        ),
        sa.Column(
            "restored_cost_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "aggregate_historical_unit_cost",
            sa.Numeric(
                precision=24,
                scale=8,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=False,
        ),
        sa.Column(
            "reversal_of_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.CheckConstraint(
            (
                "valuation_method IN "
                "('fifo', 'weighted_average_moving')"
            ),
            name=(
                "ck_srcre_event_valuation_method"
            ),
        ),
        sa.CheckConstraint(
            "restored_quantity > 0",
            name=(
                "ck_srcre_event_quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "restored_valuation_amount >= 0",
            name=(
                "ck_srcre_event_valuation_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "restored_cost_amount >= 0",
            name=(
                "ck_srcre_event_cost_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "aggregate_historical_unit_cost >= 0",
            name=(
                "ck_srcre_event_unit_cost_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            (
                "reversal_of_id IS NULL "
                "OR reversal_of_id <> id"
            ),
            name=(
                "ck_srcre_event_not_self_reversal"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
            ],
            [
                "companies.id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "created_by",
            ],
            [
                "users.id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "inventory_cost_entry_id",
            ],
            [
                "inventory_cost_entries.id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "trade_return_event_id",
            ],
            [
                "trade_return_events.company_id",
                "trade_return_events.id",
            ],
            name=(
                "fk_srcre_event_trade_return"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "reversal_of_id",
                "trade_return_event_id",
                "inventory_cost_entry_id",
            ],
            [
                (
                    "sales_return_cost_restoration_events."
                    "company_id"
                ),
                (
                    "sales_return_cost_restoration_events."
                    "id"
                ),
                (
                    "sales_return_cost_restoration_events."
                    "trade_return_event_id"
                ),
                (
                    "sales_return_cost_restoration_events."
                    "inventory_cost_entry_id"
                ),
            ],
            name=(
                "fk_srcre_event_reversal_source"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name=(
                "uq_srcre_event_company_id_id"
            ),
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "trade_return_event_id",
            "inventory_cost_entry_id",
            name=(
                "uq_srcre_event_company_id_id_source"
            ),
        ),
        sa.UniqueConstraint(
            "reversal_of_id",
            name=(
                "uq_srcre_event_reversal_of_id"
            ),
        ),
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_events_company_id"
        ),
        "sales_return_cost_restoration_events",
        [
            "company_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_events_trade_return_event_id"
        ),
        "sales_return_cost_restoration_events",
        [
            "trade_return_event_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_events_inventory_cost_entry_id"
        ),
        "sales_return_cost_restoration_events",
        [
            "inventory_cost_entry_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_events_restoration_date"
        ),
        "sales_return_cost_restoration_events",
        [
            "restoration_date",
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_events_reversal_of_id"
        ),
        "sales_return_cost_restoration_events",
        [
            "reversal_of_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_srcre_event_pair_history",
        "sales_return_cost_restoration_events",
        [
            "company_id",
            "trade_return_event_id",
            "inventory_cost_entry_id",
            "id",
        ],
        unique=False,
    )

    op.create_table(
        "sales_return_cost_restoration_fifo_slices",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            (
                "sales_return_cost_restoration_"
                "event_id"
            ),
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "fifo_consumption_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "stock_lot_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "restored_quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "historical_unit_cost",
            sa.Numeric(
                precision=24,
                scale=8,
            ),
            nullable=False,
        ),
        sa.Column(
            "restored_valuation_amount",
            sa.Numeric(
                precision=24,
                scale=8,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "restored_quantity > 0",
            name=(
                "ck_srcfs_quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "historical_unit_cost >= 0",
            name=(
                "ck_srcfs_unit_cost_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "restored_valuation_amount >= 0",
            name=(
                "ck_srcfs_valuation_nonnegative"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
            ],
            [
                "companies.id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "fifo_consumption_id",
            ],
            [
                "stock_lot_consumptions.id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "stock_lot_id",
            ],
            [
                "stock_lots.id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                (
                    "sales_return_cost_restoration_"
                    "event_id"
                ),
            ],
            [
                (
                    "sales_return_cost_restoration_events."
                    "company_id"
                ),
                (
                    "sales_return_cost_restoration_events."
                    "id"
                ),
            ],
            name=(
                "fk_srcfs_parent_event"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name=(
                "uq_srcfs_company_id_id"
            ),
        ),
        sa.UniqueConstraint(
            (
                "sales_return_cost_restoration_"
                "event_id"
            ),
            "fifo_consumption_id",
            name=(
                "uq_srcfs_event_consumption"
            ),
        ),
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_company_id"
        ),
        "sales_return_cost_restoration_fifo_slices",
        [
            "company_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_sales_return_cost_restoration_event_id"
        ),
        "sales_return_cost_restoration_fifo_slices",
        [
            (
                "sales_return_cost_restoration_"
                "event_id"
            ),
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_fifo_consumption_id"
        ),
        "sales_return_cost_restoration_fifo_slices",
        [
            "fifo_consumption_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_stock_lot_id"
        ),
        "sales_return_cost_restoration_fifo_slices",
        [
            "stock_lot_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_srcfs_fifo_provenance",
        "sales_return_cost_restoration_fifo_slices",
        [
            "company_id",
            "fifo_consumption_id",
            (
                "sales_return_cost_restoration_"
                "event_id"
            ),
        ],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_srcfs_fifo_provenance",
        table_name=(
            "sales_return_cost_restoration_fifo_slices"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_stock_lot_id"
        ),
        table_name=(
            "sales_return_cost_restoration_fifo_slices"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_fifo_consumption_id"
        ),
        table_name=(
            "sales_return_cost_restoration_fifo_slices"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_sales_return_cost_restoration_event_id"
        ),
        table_name=(
            "sales_return_cost_restoration_fifo_slices"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_fifo_slices_company_id"
        ),
        table_name=(
            "sales_return_cost_restoration_fifo_slices"
        ),
    )

    op.drop_table(
        "sales_return_cost_restoration_fifo_slices"
    )

    op.drop_index(
        "ix_srcre_event_pair_history",
        table_name=(
            "sales_return_cost_restoration_events"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_events_reversal_of_id"
        ),
        table_name=(
            "sales_return_cost_restoration_events"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_events_restoration_date"
        ),
        table_name=(
            "sales_return_cost_restoration_events"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_events_inventory_cost_entry_id"
        ),
        table_name=(
            "sales_return_cost_restoration_events"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_events_trade_return_event_id"
        ),
        table_name=(
            "sales_return_cost_restoration_events"
        ),
    )

    op.drop_index(
        op.f(
            "ix_sales_return_cost_restoration_events_company_id"
        ),
        table_name=(
            "sales_return_cost_restoration_events"
        ),
    )

    op.drop_table(
        "sales_return_cost_restoration_events"
    )
