"""add employee foundation

Revision ID: d7de4f261aa2
Revises: 8fa12512c001
Create Date: 2026-09-30 16:22:32.515178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7de4f261aa2'
down_revision: Union[str, Sequence[str], None] = '8fa12512c001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', name='employee_status'), server_default='active', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'terminated' OR termination_date IS NOT NULL", name='ck_employees_terminated_requires_date'),
    sa.CheckConstraint("status = 'terminated' OR termination_date IS NULL", name='ck_employees_nonterminated_without_termination_date'),
    sa.CheckConstraint('length(trim(employee_number)) > 0', name='ck_employees_employee_number_nonempty'),
    sa.CheckConstraint('length(trim(first_name)) > 0', name='ck_employees_first_name_nonempty'),
    sa.CheckConstraint('length(trim(last_name)) > 0', name='ck_employees_last_name_nonempty'),
    sa.CheckConstraint('termination_date IS NULL OR termination_date >= hire_date', name='ck_employees_termination_not_before_hire'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_number', name='uq_employees_company_employee_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_employees_company_id_id')
    )
    op.create_index('ix_employees_company_status', 'employees', ['company_id', 'status'], unique=False)
    op.create_index('ix_employees_company_user', 'employees', ['company_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_company_user', table_name='employees')
    op.drop_index('ix_employees_company_status', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
