"""add recalculation requests

Revision ID: d970587f9d31
Revises: 19892558ab56
Create Date: 2026-08-22 16:17:50.782472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd970587f9d31'
down_revision: Union[str, Sequence[str], None] = '19892558ab56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recalculation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('inventory', 'accounting', name='recalculation_domain_enum', native_enum=False), nullable=False),
    sa.Column('stream_key', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='recalculation_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recalculation_requests_company_id'), 'recalculation_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_recalculation_requests_domain'), 'recalculation_requests', ['domain'], unique=False)
    op.create_index(op.f('ix_recalculation_requests_effective_from'), 'recalculation_requests', ['effective_from'], unique=False)
    op.create_index(op.f('ix_recalculation_requests_request_id'), 'recalculation_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_recalculation_requests_status'), 'recalculation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_recalculation_requests_stream_key'), 'recalculation_requests', ['stream_key'], unique=False)
    op.create_index('ix_recalculation_requests_stream_status_effective', 'recalculation_requests', ['company_id', 'domain', 'stream_key', 'status', 'effective_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recalculation_requests_stream_status_effective', table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_stream_key'), table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_status'), table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_request_id'), table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_effective_from'), table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_domain'), table_name='recalculation_requests')
    op.drop_index(op.f('ix_recalculation_requests_company_id'), table_name='recalculation_requests')
    op.drop_table('recalculation_requests')
    # ### end Alembic commands ###
