"""add employment structure

Revision ID: d9dbfdb5fb99
Revises: d7de4f261aa2
Create Date: 2026-10-01 13:29:45.729013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dbfdb5fb99'
down_revision: Union[str, Sequence[str], None] = 'd7de4f261aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_departments_code_nonempty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_departments_name_nonempty'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_departments_not_self_parent'),
    sa.ForeignKeyConstraint(['company_id', 'parent_id'], ['departments.company_id', 'departments.id'], name='fk_departments_company_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_departments_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_departments_company_id_id')
    )
    op.create_index('ix_departments_company_active', 'departments', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_departments_company_parent', 'departments', ['company_id', 'parent_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_positions_code_nonempty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_positions_name_nonempty'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_positions_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_positions_company_id_id')
    )
    op.create_index('ix_positions_company_active', 'positions', ['company_id', 'is_active'], unique=False)
    op.create_table('employment_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'ended', 'cancelled', name='employment_contract_status', native_enum=False), server_default='draft', nullable=False),
    sa.Column('work_arrangement', sa.Enum('full_time', 'part_time', name='employment_work_arrangement', native_enum=False), server_default='full_time', nullable=False),
    sa.Column('workplace_type', sa.Enum('onsite', 'remote', 'hybrid', name='employment_workplace_type', native_enum=False), server_default='onsite', nullable=False),
    sa.Column('weekly_hours', sa.Integer(), server_default='40', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'ended' OR end_date IS NOT NULL", name='ck_employment_contracts_ended_requires_date'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_employment_contracts_date_range'),
    sa.CheckConstraint('length(trim(contract_number)) > 0', name='ck_employment_contracts_number_nonempty'),
    sa.CheckConstraint('weekly_hours > 0 AND weekly_hours <= 168', name='ck_employment_contracts_weekly_hours'),
    sa.ForeignKeyConstraint(['company_id', 'department_id'], ['departments.company_id', 'departments.id'], name='fk_employment_contracts_company_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employee_id'], ['employees.company_id', 'employees.id'], name='fk_employment_contracts_company_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'position_id'], ['positions.company_id', 'positions.id'], name='fk_employment_contracts_company_position', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'contract_number', name='uq_employment_contracts_company_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_employment_contracts_company_id_id')
    )
    op.create_index('ix_employment_contracts_company_department', 'employment_contracts', ['company_id', 'department_id'], unique=False)
    op.create_index('ix_employment_contracts_company_employee', 'employment_contracts', ['company_id', 'employee_id'], unique=False)
    op.create_index('ix_employment_contracts_company_position', 'employment_contracts', ['company_id', 'position_id'], unique=False)
    op.create_index('ix_employment_contracts_company_status', 'employment_contracts', ['company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employment_contracts_company_status', table_name='employment_contracts')
    op.drop_index('ix_employment_contracts_company_position', table_name='employment_contracts')
    op.drop_index('ix_employment_contracts_company_employee', table_name='employment_contracts')
    op.drop_index('ix_employment_contracts_company_department', table_name='employment_contracts')
    op.drop_table('employment_contracts')
    op.drop_index('ix_positions_company_active', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_departments_company_parent', table_name='departments')
    op.drop_index('ix_departments_company_active', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
