"""add accounting rules

Revision ID: dac3ce15642a
Revises: 6a3480215744
Create Date: 2026-08-18 12:34:02.649613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac3ce15642a'
down_revision: Union[str, Sequence[str], None] = '6a3480215744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('receipt', 'issue', 'adjustment', name='accounting_rule_document_type_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_accounting_rule_company_code')
    )
    op.create_index(op.f('ix_accounting_rules_company_id'), 'accounting_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounting_rules_document_type'), 'accounting_rules', ['document_type'], unique=False)
    op.create_table('accounting_rule_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accounting_rule_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('debit', 'credit', name='accounting_rule_side_enum', native_enum=False), nullable=False),
    sa.Column('amount_source', sa.Enum('document_total', 'line_total', name='accounting_amount_source_enum', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.CheckConstraint('line_no > 0', name='ck_accounting_rule_line_number_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['accounting_rule_id'], ['accounting_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accounting_rule_id', 'line_no', name='uq_accounting_rule_line_number')
    )
    op.create_index(op.f('ix_accounting_rule_lines_account_id'), 'accounting_rule_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_accounting_rule_lines_accounting_rule_id'), 'accounting_rule_lines', ['accounting_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_rule_lines_accounting_rule_id'), table_name='accounting_rule_lines')
    op.drop_index(op.f('ix_accounting_rule_lines_account_id'), table_name='accounting_rule_lines')
    op.drop_table('accounting_rule_lines')
    op.drop_index(op.f('ix_accounting_rules_document_type'), table_name='accounting_rules')
    op.drop_index(op.f('ix_accounting_rules_company_id'), table_name='accounting_rules')
    op.drop_table('accounting_rules')
    # ### end Alembic commands ###
