"""add vat advance bridge events

Revision ID: dc753d0ca487
Revises: d54e8c2a71f3
Create Date: 2026-09-02 15:42:43.413638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc753d0ca487'
down_revision: Union[str, Sequence[str], None] = 'd54e8c2a71f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat_advance_bridge_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tax_calculation_id', sa.Integer(), nullable=False),
    sa.Column('invoice_fulfillment_allocation_id', sa.Integer(), nullable=False),
    sa.Column('bridge_date', sa.Date(), nullable=False),
    sa.Column('bridged_tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('bridged_tax_amount > 0', name='ck_vat_advance_bridge_events_tax_amount_positive'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_vat_advance_bridge_events_currency_code_length'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_of_id <> id', name='ck_vat_advance_bridge_events_not_self_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'invoice_fulfillment_allocation_id'], ['invoice_fulfillment_allocations.company_id', 'invoice_fulfillment_allocations.id'], name='fk_vat_advance_bridge_events_company_fulfillment_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id', 'tax_calculation_id', 'invoice_fulfillment_allocation_id'], ['vat_advance_bridge_events.company_id', 'vat_advance_bridge_events.id', 'vat_advance_bridge_events.tax_calculation_id', 'vat_advance_bridge_events.invoice_fulfillment_allocation_id'], name='fk_vat_advance_bridge_events_company_reversal_of_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'tax_calculation_id'], ['tax_calculations.company_id', 'tax_calculations.id'], name='fk_vat_advance_bridge_events_company_tax_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', 'tax_calculation_id', 'invoice_fulfillment_allocation_id', name='uq_vat_advance_bridge_events_company_id_id_source'),
    sa.UniqueConstraint('company_id', 'id', name='uq_vat_advance_bridge_events_company_id_id'),
    sa.UniqueConstraint('reversal_of_id', name='uq_vat_advance_bridge_events_reversal_of')
    )
    op.create_index(op.f('ix_vat_advance_bridge_events_bridge_date'), 'vat_advance_bridge_events', ['bridge_date'], unique=False)
    op.create_index(op.f('ix_vat_advance_bridge_events_company_id'), 'vat_advance_bridge_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_vat_advance_bridge_events_invoice_fulfillment_allocation_id'), 'vat_advance_bridge_events', ['invoice_fulfillment_allocation_id'], unique=False)
    op.create_index(op.f('ix_vat_advance_bridge_events_reversal_of_id'), 'vat_advance_bridge_events', ['reversal_of_id'], unique=False)
    op.create_index('ix_vat_advance_bridge_events_source_original', 'vat_advance_bridge_events', ['company_id', 'tax_calculation_id', 'invoice_fulfillment_allocation_id', 'id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.create_index(op.f('ix_vat_advance_bridge_events_tax_calculation_id'), 'vat_advance_bridge_events', ['tax_calculation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vat_advance_bridge_events_tax_calculation_id'), table_name='vat_advance_bridge_events')
    op.drop_index('ix_vat_advance_bridge_events_source_original', table_name='vat_advance_bridge_events', postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.drop_index(op.f('ix_vat_advance_bridge_events_reversal_of_id'), table_name='vat_advance_bridge_events')
    op.drop_index(op.f('ix_vat_advance_bridge_events_invoice_fulfillment_allocation_id'), table_name='vat_advance_bridge_events')
    op.drop_index(op.f('ix_vat_advance_bridge_events_company_id'), table_name='vat_advance_bridge_events')
    op.drop_index(op.f('ix_vat_advance_bridge_events_bridge_date'), table_name='vat_advance_bridge_events')
    op.drop_table('vat_advance_bridge_events')
    # ### end Alembic commands ###
