"""add trade return correction events

Revision ID: e3f7c9a1b624
Revises: b7d4e2c9a631
"""

from typing import (
    Sequence,
    Union,
)

from alembic import op
import sqlalchemy as sa


revision: str = "e3f7c9a1b624"

down_revision: Union[
    str,
    Sequence[str],
    None,
] = "b7d4e2c9a631"

branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None

depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    op.create_table(
        "trade_return_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.String(
                length=10
            ),
            nullable=False,
        ),
        sa.Column(
            "original_fulfillment_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "original_trade_document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "original_trade_document_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "original_fulfillment_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "return_document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "return_document_type",
            sa.String(
                length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "return_document_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "return_warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "return_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "returned_quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason_code",
            sa.String(
                length=40
            ),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.Column(
            "reversal_of_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.CheckConstraint(
            "direction IN ('sale', 'purchase')",
            name="ck_tre_event_direction",
        ),
        sa.CheckConstraint(
            (
                "return_document_type "
                "IN ('receipt', 'issue')"
            ),
            name=(
                "ck_tre_event_return_document_type"
            ),
        ),
        sa.CheckConstraint(
            (
                "("
                "direction = 'sale' "
                "AND return_document_type = 'receipt'"
                ") OR ("
                "direction = 'purchase' "
                "AND return_document_type = 'issue'"
                ")"
            ),
            name=(
                "ck_tre_event_direction_document_type"
            ),
        ),
        sa.CheckConstraint(
            "returned_quantity > 0",
            name=(
                "ck_tre_event_returned_quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "reason_code IS NULL "
                "OR char_length(trim(reason_code)) > 0"
            ),
            name=(
                "ck_tre_event_reason_nonempty"
            ),
        ),
        sa.CheckConstraint(
            (
                "reversal_of_id IS NULL "
                "OR reversal_of_id <> id"
            ),
            name=(
                "ck_tre_event_not_self_reversal"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["return_warehouse_id"],
            ["warehouses.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "original_trade_document_id",
                "original_trade_document_line_id",
                "product_id",
            ],
            [
                "trade_document_lines.company_id",
                "trade_document_lines.trade_document_id",
                "trade_document_lines.id",
                "trade_document_lines.product_id",
            ],
            name=(
                "fk_tre_event_original_trade_line"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "original_fulfillment_id",
                "original_trade_document_id",
                "original_trade_document_line_id",
                "original_fulfillment_line_id",
                "product_id",
            ],
            [
                "trade_fulfillment_lines.company_id",
                "trade_fulfillment_lines.fulfillment_id",
                "trade_fulfillment_lines.trade_document_id",
                "trade_fulfillment_lines.trade_document_line_id",
                "trade_fulfillment_lines.id",
                "trade_fulfillment_lines.product_id",
            ],
            name=(
                "fk_tre_event_original_fulfillment_line"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "return_document_id",
                "return_document_type",
            ],
            [
                "documents.company_id",
                "documents.id",
                "documents.document_type",
            ],
            name=(
                "fk_tre_event_return_document"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "return_document_id",
                "return_document_line_id",
                "product_id",
                "return_warehouse_id",
            ],
            [
                "document_lines.document_id",
                "document_lines.id",
                "document_lines.product_id",
                "document_lines.warehouse_id",
            ],
            name=(
                "fk_tre_event_return_document_line"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "reversal_of_id",
                "direction",
                "original_fulfillment_id",
                "original_trade_document_id",
                "original_trade_document_line_id",
                "original_fulfillment_line_id",
                "product_id",
                "return_document_id",
                "return_document_type",
                "return_document_line_id",
                "return_warehouse_id",
            ],
            [
                "trade_return_events.company_id",
                "trade_return_events.id",
                "trade_return_events.direction",
                "trade_return_events.original_fulfillment_id",
                (
                    "trade_return_events."
                    "original_trade_document_id"
                ),
                (
                    "trade_return_events."
                    "original_trade_document_line_id"
                ),
                (
                    "trade_return_events."
                    "original_fulfillment_line_id"
                ),
                "trade_return_events.product_id",
                "trade_return_events.return_document_id",
                "trade_return_events.return_document_type",
                "trade_return_events.return_document_line_id",
                "trade_return_events.return_warehouse_id",
            ],
            name=(
                "fk_tre_event_reversal_source"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name="uq_tre_event_company_id_id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "direction",
            "original_fulfillment_id",
            "original_trade_document_id",
            "original_trade_document_line_id",
            "original_fulfillment_line_id",
            "product_id",
            "return_document_id",
            "return_document_type",
            "return_document_line_id",
            "return_warehouse_id",
            name=(
                "uq_tre_event_company_id_id_source"
            ),
        ),
        sa.UniqueConstraint(
            "reversal_of_id",
            name=(
                "uq_tre_event_reversal_of"
            ),
        ),
    )

    op.create_index(
        "uq_tre_event_original_return_line",
        "trade_return_events",
        [
            "company_id",
            "return_document_id",
            "return_document_line_id",
        ],
        unique=True,
        postgresql_where=sa.text(
            "reversal_of_id IS NULL"
        ),
    )

    op.create_index(
        "ix_tre_event_original_fulfillment_source",
        "trade_return_events",
        [
            "company_id",
            "original_fulfillment_id",
            "original_fulfillment_line_id",
            "return_date",
            "id",
        ],
        unique=False,
    )

    op.create_table(
        "trade_value_correction_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.String(
                length=10
            ),
            nullable=False,
        ),
        sa.Column(
            "trade_document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "trade_document_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "correction_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "original_gross_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "original_tax_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "corrected_gross_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "corrected_tax_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "currency_code",
            sa.String(
                length=3
            ),
            nullable=False,
        ),
        sa.Column(
            "reason_code",
            sa.String(
                length=40
            ),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.Column(
            "reversal_of_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.CheckConstraint(
            "direction IN ('sale', 'purchase')",
            name=(
                "ck_tvce_event_direction"
            ),
        ),
        sa.CheckConstraint(
            "original_gross_amount >= 0",
            name=(
                "ck_tvce_event_original_gross_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "original_tax_amount >= 0",
            name=(
                "ck_tvce_event_original_tax_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            (
                "original_tax_amount "
                "<= original_gross_amount"
            ),
            name=(
                "ck_tvce_event_original_tax_not_above_gross"
            ),
        ),
        sa.CheckConstraint(
            "corrected_gross_amount >= 0",
            name=(
                "ck_tvce_event_corrected_gross_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "corrected_tax_amount >= 0",
            name=(
                "ck_tvce_event_corrected_tax_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            (
                "corrected_tax_amount "
                "<= corrected_gross_amount"
            ),
            name=(
                "ck_tvce_event_corrected_tax_not_above_gross"
            ),
        ),
        sa.CheckConstraint(
            (
                "original_gross_amount "
                "<> corrected_gross_amount "
                "OR original_tax_amount "
                "<> corrected_tax_amount"
            ),
            name=(
                "ck_tvce_event_not_noop"
            ),
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3",
            name=(
                "ck_tvce_event_currency_length"
            ),
        ),
        sa.CheckConstraint(
            (
                "reason_code IS NULL "
                "OR char_length(trim(reason_code)) > 0"
            ),
            name=(
                "ck_tvce_event_reason_nonempty"
            ),
        ),
        sa.CheckConstraint(
            (
                "reversal_of_id IS NULL "
                "OR reversal_of_id <> id"
            ),
            name=(
                "ck_tvce_event_not_self_reversal"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "trade_document_id",
                "trade_document_line_id",
                "product_id",
            ],
            [
                "trade_document_lines.company_id",
                "trade_document_lines.trade_document_id",
                "trade_document_lines.id",
                "trade_document_lines.product_id",
            ],
            name=(
                "fk_tvce_event_trade_document_line"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "reversal_of_id",
                "direction",
                "trade_document_id",
                "trade_document_line_id",
                "product_id",
            ],
            [
                "trade_value_correction_events.company_id",
                "trade_value_correction_events.id",
                "trade_value_correction_events.direction",
                (
                    "trade_value_correction_events."
                    "trade_document_id"
                ),
                (
                    "trade_value_correction_events."
                    "trade_document_line_id"
                ),
                (
                    "trade_value_correction_events."
                    "product_id"
                ),
            ],
            name=(
                "fk_tvce_event_reversal_source"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name=(
                "uq_tvce_event_company_id_id"
            ),
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "direction",
            "trade_document_id",
            "trade_document_line_id",
            "product_id",
            name=(
                "uq_tvce_event_company_id_id_source"
            ),
        ),
        sa.UniqueConstraint(
            "reversal_of_id",
            name=(
                "uq_tvce_event_reversal_of"
            ),
        ),
    )

    op.create_index(
        "ix_tvce_event_trade_document_line",
        "trade_value_correction_events",
        [
            "company_id",
            "trade_document_id",
            "trade_document_line_id",
            "correction_date",
            "id",
        ],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_tvce_event_trade_document_line",
        table_name=(
            "trade_value_correction_events"
        ),
    )

    op.drop_table(
        "trade_value_correction_events"
    )

    op.drop_index(
        "ix_tre_event_original_fulfillment_source",
        table_name=(
            "trade_return_events"
        ),
    )

    op.drop_index(
        "uq_tre_event_original_return_line",
        table_name=(
            "trade_return_events"
        ),
    )

    op.drop_table(
        "trade_return_events"
    )
