"""add fixed asset directories and card history

Revision ID: e50a0439ab4c
Revises: 0a3d68a376e7
Create Date: 2026-09-25 21:49:25.169564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50a0439ab4c'
down_revision: Union[str, Sequence[str], None] = '0a3d68a376e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_fixed_asset_groups_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_fixed_asset_groups_company_id_id')
    )
    op.create_index('ix_fixed_asset_groups_company_active', 'fixed_asset_groups', ['company_id', 'is_active'], unique=False)
    op.create_table('fixed_asset_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_fixed_asset_locations_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_fixed_asset_locations_company_id_id')
    )
    op.create_index('ix_fixed_asset_locations_company_active', 'fixed_asset_locations', ['company_id', 'is_active'], unique=False)
    op.create_table('fixed_asset_responsible_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_fixed_asset_responsible_persons_company_id_id')
    )
    op.create_index('ix_fixed_asset_responsible_persons_company_active', 'fixed_asset_responsible_persons', ['company_id', 'is_active'], unique=False)
    op.create_table('fixed_asset_card_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('asset_group_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('responsible_person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('depreciation_method', sa.Enum('STRAIGHT_LINE', 'DIMINISHING_BALANCE', 'DOUBLE_DIMINISHING_BALANCE', 'CUMULATIVE', 'PRODUCTION', name='fixed_asset_depreciation_method', native_enum=False), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'asset_group_id'], ['fixed_asset_groups.company_id', 'fixed_asset_groups.id'], name='fk_fixed_asset_card_history_company_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'fixed_asset_id'], ['fixed_assets.company_id', 'fixed_assets.id'], name='fk_fixed_asset_card_history_company_asset', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'location_id'], ['fixed_asset_locations.company_id', 'fixed_asset_locations.id'], name='fk_fixed_asset_card_history_company_location', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'responsible_person_id'], ['fixed_asset_responsible_persons.company_id', 'fixed_asset_responsible_persons.id'], name='fk_fixed_asset_card_history_company_responsible', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fixed_asset_card_history_company_asset_effective', 'fixed_asset_card_history', ['company_id', 'fixed_asset_id', 'effective_date'], unique=False)
    op.add_column('fixed_assets', sa.Column('asset_group_id', sa.Integer(), nullable=False))
    op.add_column('fixed_assets', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('fixed_assets', sa.Column('responsible_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_fixed_assets_company_location', 'fixed_assets', 'fixed_asset_locations', ['company_id', 'location_id'], ['company_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_fixed_assets_company_responsible_person', 'fixed_assets', 'fixed_asset_responsible_persons', ['company_id', 'responsible_person_id'], ['company_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_fixed_assets_company_asset_group', 'fixed_assets', 'fixed_asset_groups', ['company_id', 'asset_group_id'], ['company_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_fixed_assets_company_asset_group', 'fixed_assets', type_='foreignkey')
    op.drop_constraint('fk_fixed_assets_company_responsible_person', 'fixed_assets', type_='foreignkey')
    op.drop_constraint('fk_fixed_assets_company_location', 'fixed_assets', type_='foreignkey')
    op.drop_column('fixed_assets', 'responsible_person_id')
    op.drop_column('fixed_assets', 'location_id')
    op.drop_column('fixed_assets', 'asset_group_id')
    op.drop_index('ix_fixed_asset_card_history_company_asset_effective', table_name='fixed_asset_card_history')
    op.drop_table('fixed_asset_card_history')
    op.drop_index('ix_fixed_asset_responsible_persons_company_active', table_name='fixed_asset_responsible_persons')
    op.drop_table('fixed_asset_responsible_persons')
    op.drop_index('ix_fixed_asset_locations_company_active', table_name='fixed_asset_locations')
    op.drop_table('fixed_asset_locations')
    op.drop_index('ix_fixed_asset_groups_company_active', table_name='fixed_asset_groups')
    op.drop_table('fixed_asset_groups')
    # ### end Alembic commands ###
