"""add payroll correction revision foundation

Revision ID: e69c41b1db42
Revises: 66dbc02f1c35
Create Date: 2026-10-07 13:44:00.145182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69c41b1db42'
down_revision: Union[str, Sequence[str], None] = '66dbc02f1c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('original_payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('replacement_payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'original_payroll_calculation_id'], ['payroll_calculations.company_id', 'payroll_calculations.id'], name='fk_payroll_corrections_company_original_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'replacement_payroll_calculation_id'], ['payroll_calculations.company_id', 'payroll_calculations.id'], name='fk_payroll_corrections_company_replacement_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_corrections_company_id_id'),
    sa.UniqueConstraint('company_id', 'replacement_payroll_calculation_id', name='uq_payroll_corrections_company_replacement'),
    sa.UniqueConstraint('company_id', 'request_key', name='uq_payroll_corrections_company_request')
    )
    op.create_index('ix_payroll_corrections_company_original', 'payroll_corrections', ['company_id', 'original_payroll_calculation_id'], unique=False)
    op.add_column('payroll_calculations', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint(op.f('uq_payroll_calculations_company_period_contract'), 'payroll_calculations', type_='unique')
    op.create_unique_constraint('uq_payroll_calculations_company_period_contract_revision', 'payroll_calculations', ['company_id', 'payroll_period_id', 'employment_contract_id', 'revision'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payroll_calculations_company_period_contract_revision', 'payroll_calculations', type_='unique')
    op.create_unique_constraint(op.f('uq_payroll_calculations_company_period_contract'), 'payroll_calculations', ['company_id', 'payroll_period_id', 'employment_contract_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('payroll_calculations', 'revision')
    op.drop_index('ix_payroll_corrections_company_original', table_name='payroll_corrections')
    op.drop_table('payroll_corrections')
    # ### end Alembic commands ###
