"""add trade line tax price mode

Revision ID: ea89bcd571ae
Revises: f4a88520bed5
Create Date: 2026-08-29 19:29:14.331862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea89bcd571ae'
down_revision: Union[str, Sequence[str], None] = 'f4a88520bed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_document_lines', sa.Column('tax_price_mode', sa.Enum('exclusive', 'inclusive', name='trade_document_line_tax_price_mode_enum', native_enum=False, length=20), nullable=True))
    op.create_check_constraint('ck_trade_document_line_tax_price_config_pair', 'trade_document_lines', '(tax_rate_code IS NULL AND tax_price_mode IS NULL) OR (tax_rate_code IS NOT NULL AND tax_price_mode IS NOT NULL)')
    op.create_check_constraint('ck_trade_document_line_tax_price_mode', 'trade_document_lines', "tax_price_mode IS NULL OR tax_price_mode IN ('exclusive', 'inclusive')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_trade_document_line_tax_price_mode', 'trade_document_lines', type_='check')
    op.drop_constraint('ck_trade_document_line_tax_price_config_pair', 'trade_document_lines', type_='check')
    op.drop_column('trade_document_lines', 'tax_price_mode')
    # ### end Alembic commands ###
