"""add inventory cost entries

Revision ID: eb070f26955f
Revises: fa75caf97ad2
Create Date: 2026-08-19 12:29:30.561689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb070f26955f'
down_revision: Union[str, Sequence[str], None] = 'fa75caf97ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_cost_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_line_id', sa.Integer(), nullable=False),
    sa.Column('valuation_method', sa.Enum('fifo', 'weighted_average_moving', 'weighted_average_periodic', 'identified_cost', 'standard_cost', 'retail_price', name='inventory_valuation_method_enum', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost_amount >= 0', name='ck_inventory_cost_entry_amount_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_cost_entry_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_inventory_cost_entry_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_line_id'], ['document_lines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_line_id', name='uq_inventory_cost_entry_document_line')
    )
    op.create_index(op.f('ix_inventory_cost_entries_company_id'), 'inventory_cost_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_cost_entries_document_id'), 'inventory_cost_entries', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_cost_entries_document_id'), table_name='inventory_cost_entries')
    op.drop_index(op.f('ix_inventory_cost_entries_company_id'), table_name='inventory_cost_entries')
    op.drop_table('inventory_cost_entries')
    # ### end Alembic commands ###
