"""add persistent tax recognition events

Revision ID: ec24630a3445
Revises: 041c0168af79
Create Date: 2026-08-29 18:46:18.615482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec24630a3445'
down_revision: Union[str, Sequence[str], None] = '041c0168af79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_recognition_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tax_calculation_id', sa.Integer(), nullable=False),
    sa.Column('invoice_fulfillment_allocation_id', sa.Integer(), nullable=True),
    sa.Column('payment_settlement_allocation_id', sa.Integer(), nullable=True),
    sa.Column('recognition_date', sa.Date(), nullable=False),
    sa.Column('recognized_taxable_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recognized_tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('\n            invoice_fulfillment_allocation_id IS NULL\n            OR payment_settlement_allocation_id IS NULL\n            ', name='ck_tax_recognition_events_at_most_one_recognition_source'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_tax_recognition_events_currency_code_length'),
    sa.CheckConstraint('recognized_tax_amount >= 0', name='ck_tax_recognition_events_tax_amount_nonnegative'),
    sa.CheckConstraint('recognized_taxable_base > 0 OR recognized_tax_amount > 0', name='ck_tax_recognition_events_nonzero_recognition'),
    sa.CheckConstraint('recognized_taxable_base >= 0', name='ck_tax_recognition_events_taxable_base_nonnegative'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_of_id <> id', name='ck_tax_recognition_events_not_self_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'invoice_fulfillment_allocation_id'], ['invoice_fulfillment_allocations.company_id', 'invoice_fulfillment_allocations.id'], name='fk_tax_recognition_events_company_invoice_fulfillment_alloc', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payment_settlement_allocation_id'], ['payment_settlement_allocations.company_id', 'payment_settlement_allocations.id'], name='fk_tax_recognition_events_company_payment_settlement_allocation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'reversal_of_id', 'tax_calculation_id'], ['tax_recognition_events.company_id', 'tax_recognition_events.id', 'tax_recognition_events.tax_calculation_id'], name='fk_tax_recognition_events_company_reversal_of_tax_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'tax_calculation_id'], ['tax_calculations.company_id', 'tax_calculations.id'], name='fk_tax_recognition_events_company_tax_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', 'tax_calculation_id', name='uq_tax_recognition_events_company_id_id_tax_calculation'),
    sa.UniqueConstraint('company_id', 'id', name='uq_tax_recognition_events_company_id_id'),
    sa.UniqueConstraint('reversal_of_id', name='uq_tax_recognition_events_reversal_of')
    )
    op.create_index(op.f('ix_tax_recognition_events_company_id'), 'tax_recognition_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_tax_recognition_events_invoice_fulfillment_allocation_id'), 'tax_recognition_events', ['invoice_fulfillment_allocation_id'], unique=False)
    op.create_index(op.f('ix_tax_recognition_events_payment_settlement_allocation_id'), 'tax_recognition_events', ['payment_settlement_allocation_id'], unique=False)
    op.create_index(op.f('ix_tax_recognition_events_recognition_date'), 'tax_recognition_events', ['recognition_date'], unique=False)
    op.create_index(op.f('ix_tax_recognition_events_reversal_of_id'), 'tax_recognition_events', ['reversal_of_id'], unique=False)
    op.create_index(op.f('ix_tax_recognition_events_tax_calculation_id'), 'tax_recognition_events', ['tax_calculation_id'], unique=False)
    op.create_index('ix_tax_recognition_events_tax_calculation_original', 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'id'], unique=False, postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.create_index('uq_tax_recognition_events_original_fulfillment_source', 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'invoice_fulfillment_allocation_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NULL AND invoice_fulfillment_allocation_id IS NOT NULL'))
    op.create_index('uq_tax_recognition_events_original_settlement_source', 'tax_recognition_events', ['company_id', 'tax_calculation_id', 'payment_settlement_allocation_id'], unique=True, postgresql_where=sa.text('reversal_of_id IS NULL AND payment_settlement_allocation_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tax_recognition_events_original_settlement_source', table_name='tax_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL AND payment_settlement_allocation_id IS NOT NULL'))
    op.drop_index('uq_tax_recognition_events_original_fulfillment_source', table_name='tax_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL AND invoice_fulfillment_allocation_id IS NOT NULL'))
    op.drop_index('ix_tax_recognition_events_tax_calculation_original', table_name='tax_recognition_events', postgresql_where=sa.text('reversal_of_id IS NULL'))
    op.drop_index(op.f('ix_tax_recognition_events_tax_calculation_id'), table_name='tax_recognition_events')
    op.drop_index(op.f('ix_tax_recognition_events_reversal_of_id'), table_name='tax_recognition_events')
    op.drop_index(op.f('ix_tax_recognition_events_recognition_date'), table_name='tax_recognition_events')
    op.drop_index(op.f('ix_tax_recognition_events_payment_settlement_allocation_id'), table_name='tax_recognition_events')
    op.drop_index(op.f('ix_tax_recognition_events_invoice_fulfillment_allocation_id'), table_name='tax_recognition_events')
    op.drop_index(op.f('ix_tax_recognition_events_company_id'), table_name='tax_recognition_events')
    op.drop_table('tax_recognition_events')
    # ### end Alembic commands ###
