"""add order linked VAT advances and transfer history

Revision ID: f3bac6e8a157
Revises: e2a9c5d7f046
Create Date: 2026-09-16 17:07:43.767618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bac6e8a157'
down_revision: Union[str, Sequence[str], None] = 'e2a9c5d7f046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_vat_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status='active' AND invoice_id IS NULL AND closed_at IS NULL AND closed_by IS NULL) OR (status='transferred' AND invoice_id IS NOT NULL AND closed_at IS NOT NULL AND closed_by IS NOT NULL) OR (status='reversed' AND invoice_id IS NULL AND closed_at IS NOT NULL AND closed_by IS NOT NULL)", name='ck_ova_lifecycle'),
    sa.CheckConstraint("amount > 0 AND amount < 'Infinity'::numeric", name='ck_ova_amount'),
    sa.CheckConstraint("status IN ('active','transferred','reversed')", name='ck_ova_status'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'invoice_id'], ['trade_documents.company_id', 'trade_documents.id'], name='fk_ova_invoice', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'order_id'], ['trade_documents.company_id', 'trade_documents.id'], name='fk_ova_order', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'payment_id'], ['payments.company_id', 'payments.id'], name='fk_ova_payment', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ova_company_id'),
    sa.UniqueConstraint('company_id', 'payment_id', name='uq_ova_payment')
    )
    op.create_table('order_vat_advance_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('advance_id', sa.Integer(), nullable=False),
    sa.Column('tax_calculation_id', sa.Integer(), nullable=False),
    sa.Column('base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint("base >= 0 AND tax >= 0 AND gross > 0 AND gross < 'Infinity'::numeric AND gross = base + tax", name='ck_oval_amounts'),
    sa.ForeignKeyConstraint(['company_id', 'advance_id'], ['order_vat_advances.company_id', 'order_vat_advances.id'], name='fk_oval_advance', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'tax_calculation_id'], ['tax_calculations.company_id', 'tax_calculations.id'], name='fk_oval_calc', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advance_id', 'tax_calculation_id', name='uq_oval_calculation')
    )
    op.create_table('order_vat_advance_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('advance_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(reversed_at IS NULL) = (reversed_by IS NULL)', name='ck_ovat_reversal'),
    sa.ForeignKeyConstraint(['company_id', 'advance_id'], ['order_vat_advances.company_id', 'order_vat_advances.id'], name='fk_ovat_advance', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'allocation_id'], ['payment_settlement_allocations.company_id', 'payment_settlement_allocations.id'], name='fk_ovat_allocation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id', name='uq_ovat_allocation')
    )
    op.add_column('tax_recognition_events', sa.Column('order_vat_advance_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tre_order_advance', 'tax_recognition_events', 'order_vat_advances', ['company_id', 'order_vat_advance_id'], ['company_id', 'id'], ondelete='RESTRICT')
    op.drop_constraint('ck_tax_recognition_events_at_most_one_recognition_source', 'tax_recognition_events', type_='check')
    op.create_check_constraint('ck_tax_recognition_events_at_most_one_recognition_source', 'tax_recognition_events',
        'num_nonnulls(invoice_fulfillment_allocation_id, payment_settlement_allocation_id, tax_credit_evidence_id, order_vat_advance_id) <= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tax_recognition_events_at_most_one_recognition_source', 'tax_recognition_events', type_='check')
    op.create_check_constraint('ck_tax_recognition_events_at_most_one_recognition_source', 'tax_recognition_events',
        'num_nonnulls(invoice_fulfillment_allocation_id, payment_settlement_allocation_id, tax_credit_evidence_id) <= 1')
    op.drop_constraint('fk_tre_order_advance', 'tax_recognition_events', type_='foreignkey')
    op.drop_column('tax_recognition_events', 'order_vat_advance_id')
    op.drop_table('order_vat_advance_transfers')
    op.drop_table('order_vat_advance_lines')
    op.drop_table('order_vat_advances')
    # ### end Alembic commands ###
