"""add trade line vat configuration

Revision ID: f4a88520bed5
Revises: ec24630a3445
Create Date: 2026-08-29 19:27:09.485494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a88520bed5'
down_revision: Union[str, Sequence[str], None] = 'ec24630a3445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_document_lines', sa.Column('tax_rate_code', sa.String(length=50), nullable=True))
    op.add_column('trade_document_lines', sa.Column('tax_recognition_method', sa.Enum('first_event', 'cash_method', 'manual', name='trade_document_line_tax_recognition_method_enum', native_enum=False, length=20), nullable=True))
    op.create_check_constraint('ck_trade_document_line_tax_config_pair', 'trade_document_lines', '(tax_rate_code IS NULL AND tax_recognition_method IS NULL) OR (tax_rate_code IS NOT NULL AND tax_recognition_method IS NOT NULL)')
    op.create_check_constraint('ck_trade_document_line_tax_rate_code_nonempty', 'trade_document_lines', 'tax_rate_code IS NULL OR length(trim(tax_rate_code)) > 0')
    op.create_check_constraint('ck_trade_document_line_tax_recognition_method', 'trade_document_lines', "tax_recognition_method IS NULL OR tax_recognition_method IN ('first_event', 'cash_method', 'manual')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_trade_document_line_tax_recognition_method', 'trade_document_lines', type_='check')
    op.drop_constraint('ck_trade_document_line_tax_rate_code_nonempty', 'trade_document_lines', type_='check')
    op.drop_constraint('ck_trade_document_line_tax_config_pair', 'trade_document_lines', type_='check')
    op.drop_column('trade_document_lines', 'tax_recognition_method')
    op.drop_column('trade_document_lines', 'tax_rate_code')
    # ### end Alembic commands ###
