"""add warehouse transfer and inventory count

Revision ID: f4c2a91b7e63
Revises: d91f6a2c4e70
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f4c2a91b7e63"
down_revision: str | None = "d91f6a2c4e70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ---------------------------------------------------------
    # WAREHOUSE TRANSFER HEADER
    # ---------------------------------------------------------

    op.create_table(
        "warehouse_transfer_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "history_key",
            sa.String(length=36),
            nullable=False,
        ),
        sa.Column(
            "source_warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "destination_warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "transfer_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "reversal_of_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_warehouse_id <> destination_warehouse_id",
            name="ck_wte_distinct_warehouses",
        ),
        sa.CheckConstraint(
            "reversal_of_id IS NULL OR reversal_of_id <> id",
            name="ck_wte_not_self_reversal",
        ),
        sa.CheckConstraint(
            "length(history_key) = 36",
            name="ck_wte_history_key_length",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_wte_company",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_wte_created_by",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "source_warehouse_id",
            ],
            [
                "warehouses.company_id",
                "warehouses.id",
            ],
            name="fk_wte_company_source_warehouse",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "destination_warehouse_id",
            ],
            [
                "warehouses.company_id",
                "warehouses.id",
            ],
            name="fk_wte_company_destination_warehouse",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "reversal_of_id",
                "history_key",
            ],
            [
                "warehouse_transfer_events.company_id",
                "warehouse_transfer_events.id",
                "warehouse_transfer_events.history_key",
            ],
            name="fk_wte_history_reversal_of",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_warehouse_transfer_events",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name="uq_wte_company_id_id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "history_key",
            name="uq_wte_history_identity",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "source_warehouse_id",
            "destination_warehouse_id",
            name="uq_wte_line_parent_identity",
        ),
        sa.UniqueConstraint(
            "reversal_of_id",
            name="uq_wte_reversal_of",
        ),
    )

    op.create_index(
        "ix_warehouse_transfer_events_company_id",
        "warehouse_transfer_events",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_warehouse_transfer_events_source_warehouse_id",
        "warehouse_transfer_events",
        ["source_warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_warehouse_transfer_events_destination_warehouse_id",
        "warehouse_transfer_events",
        ["destination_warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_warehouse_transfer_events_transfer_date",
        "warehouse_transfer_events",
        ["transfer_date"],
        unique=False,
    )
    op.create_index(
        "ix_warehouse_transfer_events_reversal_of_id",
        "warehouse_transfer_events",
        ["reversal_of_id"],
        unique=False,
    )
    op.create_index(
        "ix_wte_company_transfer_date",
        "warehouse_transfer_events",
        [
            "company_id",
            "transfer_date",
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "ix_warehouse_transfer_events_history_key",
        "warehouse_transfer_events",
        ["history_key"],
        unique=False,
    )
    op.create_index(
        "ix_wte_history_chain",
        "warehouse_transfer_events",
        [
            "company_id",
            "history_key",
            "id",
        ],
        unique=False,
    )

    # ---------------------------------------------------------
    # PAIRED TRANSFER LINE
    # ---------------------------------------------------------

    op.create_table(
        "warehouse_transfer_lines",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "transfer_event_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "source_warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "destination_warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "issue_document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "issue_document_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "issue_document_type",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "receipt_document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "receipt_document_type",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name="ck_wtl_quantity_positive",
        ),
        sa.CheckConstraint(
            "source_warehouse_id <> destination_warehouse_id",
            name="ck_wtl_distinct_warehouses",
        ),
        sa.CheckConstraint(
            "issue_document_type = 'issue'",
            name="ck_wtl_issue_document_type",
        ),
        sa.CheckConstraint(
            "receipt_document_type = 'receipt'",
            name="ck_wtl_receipt_document_type",
        ),
        sa.CheckConstraint(
            "issue_document_id <> receipt_document_id",
            name="ck_wtl_distinct_documents",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "transfer_event_id",
                "source_warehouse_id",
                "destination_warehouse_id",
            ],
            [
                "warehouse_transfer_events.company_id",
                "warehouse_transfer_events.id",
                "warehouse_transfer_events.source_warehouse_id",
                "warehouse_transfer_events.destination_warehouse_id",
            ],
            name="fk_wtl_transfer_parent_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "issue_document_id",
                "issue_document_type",
            ],
            [
                "documents.company_id",
                "documents.id",
                "documents.document_type",
            ],
            name="fk_wtl_company_issue_document",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "receipt_document_id",
                "receipt_document_type",
            ],
            [
                "documents.company_id",
                "documents.id",
                "documents.document_type",
            ],
            name="fk_wtl_company_receipt_document",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "issue_document_id",
                "issue_document_line_id",
                "product_id",
                "source_warehouse_id",
            ],
            [
                "document_lines.document_id",
                "document_lines.id",
                "document_lines.product_id",
                "document_lines.warehouse_id",
            ],
            name="fk_wtl_issue_document_line",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_warehouse_transfer_lines",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "product_id",
            "destination_warehouse_id",
            "receipt_document_id",
            name="uq_wtl_valuation_parent_identity",
        ),
        sa.UniqueConstraint(
            "issue_document_line_id",
            name="uq_wtl_issue_document_line",
        ),
    )

    for column_name in (
        "company_id",
        "transfer_event_id",
        "product_id",
        "source_warehouse_id",
        "destination_warehouse_id",
        "issue_document_id",
        "issue_document_line_id",
        "receipt_document_id",
    ):
        op.create_index(
            f"ix_warehouse_transfer_lines_{column_name}",
            "warehouse_transfer_lines",
            [column_name],
            unique=False,
        )

    op.create_index(
        "ix_wtl_transfer_event",
        "warehouse_transfer_lines",
        [
            "company_id",
            "transfer_event_id",
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "ix_wtl_product",
        "warehouse_transfer_lines",
        [
            "company_id",
            "product_id",
            "id",
        ],
        unique=False,
    )

    # ---------------------------------------------------------
    # TRANSFER VALUATION LAYERS
    # ---------------------------------------------------------

    op.create_table(
        "warehouse_transfer_valuation_layers",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "transfer_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "destination_warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "valuation_method",
            sa.String(length=25),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(18, 4),
            nullable=False,
        ),
        sa.Column(
            "unit_cost",
            sa.Numeric(20, 8),
            nullable=False,
        ),
        sa.Column(
            "valuation_amount",
            sa.Numeric(20, 8),
            nullable=False,
        ),
        sa.Column(
            "source_inventory_cost_entry_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "source_stock_lot_consumption_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "destination_receipt_document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "destination_receipt_document_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name="ck_wtvl_quantity_positive",
        ),
        sa.CheckConstraint(
            "unit_cost >= 0",
            name="ck_wtvl_unit_cost_nonnegative",
        ),
        sa.CheckConstraint(
            "valuation_amount >= 0",
            name="ck_wtvl_valuation_amount_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "transfer_line_id",
                "product_id",
                "destination_warehouse_id",
                "destination_receipt_document_id",
            ],
            [
                "warehouse_transfer_lines.company_id",
                "warehouse_transfer_lines.id",
                "warehouse_transfer_lines.product_id",
                "warehouse_transfer_lines.destination_warehouse_id",
                "warehouse_transfer_lines.receipt_document_id",
            ],
            name="fk_wtvl_transfer_line_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "destination_receipt_document_id",
                "destination_receipt_document_line_id",
                "product_id",
                "destination_warehouse_id",
            ],
            [
                "document_lines.document_id",
                "document_lines.id",
                "document_lines.product_id",
                "document_lines.warehouse_id",
            ],
            name="fk_wtvl_destination_receipt_line",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "source_inventory_cost_entry_id",
            ],
            [
                "inventory_cost_entries.id",
            ],
            name="fk_wtvl_source_inventory_cost_entry",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "source_stock_lot_consumption_id",
            ],
            [
                "stock_lot_consumptions.id",
            ],
            name="fk_wtvl_source_fifo_consumption",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_warehouse_transfer_valuation_layers",
        ),
        sa.UniqueConstraint(
            "destination_receipt_document_line_id",
            name="uq_wtvl_destination_receipt_line",
        ),
        sa.UniqueConstraint(
            "source_stock_lot_consumption_id",
            name="uq_wtvl_source_fifo_consumption",
        ),
    )

    for column_name in (
        "company_id",
        "transfer_line_id",
        "product_id",
        "destination_warehouse_id",
        "source_inventory_cost_entry_id",
        "source_stock_lot_consumption_id",
        "destination_receipt_document_id",
        "destination_receipt_document_line_id",
    ):
        op.create_index(
            f"ix_wtvl_{column_name}",
            "warehouse_transfer_valuation_layers",
            [column_name],
            unique=False,
        )

    op.create_index(
        "ix_wtvl_transfer_line",
        "warehouse_transfer_valuation_layers",
        [
            "company_id",
            "transfer_line_id",
            "id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_wtvl_source_inventory_cost_entry",
        "warehouse_transfer_valuation_layers",
        [
            "source_inventory_cost_entry_id",
            "id",
        ],
        unique=False,
    )

    # ---------------------------------------------------------
    # INVENTORY COUNT SNAPSHOT
    # ---------------------------------------------------------

    op.create_table(
        "inventory_count_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "history_key",
            sa.String(length=36),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "count_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "expected_quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "counted_quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "reversal_of_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_quantity >= 0",
            name="ck_icev_expected_quantity_nonnegative",
        ),
        sa.CheckConstraint(
            "counted_quantity >= 0",
            name="ck_icev_counted_quantity_nonnegative",
        ),
        sa.CheckConstraint(
            "reversal_of_id IS NULL OR reversal_of_id <> id",
            name="ck_icev_not_self_reversal",
        ),
        sa.CheckConstraint(
            "length(history_key) = 36",
            name="ck_icev_history_key_length",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_icev_company",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_icev_created_by",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "product_id",
            ],
            [
                "products.company_id",
                "products.id",
            ],
            name="fk_icev_company_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "warehouse_id",
            ],
            [
                "warehouses.company_id",
                "warehouses.id",
            ],
            name="fk_icev_company_warehouse",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "reversal_of_id",
                "history_key",
            ],
            [
                "inventory_count_events.company_id",
                "inventory_count_events.id",
                "inventory_count_events.history_key",
            ],
            name="fk_icev_history_reversal_of",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_inventory_count_events",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            name="uq_icev_company_id_id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "history_key",
            name="uq_icev_history_identity",
        ),
        sa.UniqueConstraint(
            "company_id",
            "id",
            "product_id",
            "warehouse_id",
            name="uq_icev_variance_parent_identity",
        ),
        sa.UniqueConstraint(
            "reversal_of_id",
            name="uq_icev_reversal_of",
        ),
    )

    for column_name in (
        "company_id",
        "product_id",
        "warehouse_id",
        "count_date",
        "reversal_of_id",
    ):
        op.create_index(
            f"ix_inventory_count_events_{column_name}",
            "inventory_count_events",
            [column_name],
            unique=False,
        )

    op.create_index(
        "ix_icev_stock_identity",
        "inventory_count_events",
        [
            "company_id",
            "product_id",
            "warehouse_id",
            "count_date",
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "ix_inventory_count_events_history_key",
        "inventory_count_events",
        ["history_key"],
        unique=False,
    )
    op.create_index(
        "ix_icev_history_chain",
        "inventory_count_events",
        [
            "company_id",
            "history_key",
            "id",
        ],
        unique=False,
    )

    # ---------------------------------------------------------
    # INVENTORY COUNT NON-ZERO VARIANCE
    # ---------------------------------------------------------

    op.create_table(
        "inventory_count_variance_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "inventory_count_event_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "document_line_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "document_type",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "warehouse_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "adjustment_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.String(length=8),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(
                precision=18,
                scale=4,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name="ck_icve_quantity_positive",
        ),
        sa.CheckConstraint(
            "direction IN ('increase', 'decrease')",
            name="ck_icve_direction",
        ),
        sa.CheckConstraint(
            "document_type = 'adjustment'",
            name="ck_icve_document_type_adjustment",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "inventory_count_event_id",
                "product_id",
                "warehouse_id",
            ],
            [
                "inventory_count_events.company_id",
                "inventory_count_events.id",
                "inventory_count_events.product_id",
                "inventory_count_events.warehouse_id",
            ],
            name="fk_icve_count_stock_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "company_id",
                "document_id",
                "document_type",
            ],
            [
                "documents.company_id",
                "documents.id",
                "documents.document_type",
            ],
            name="fk_icve_company_adjustment_document",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "document_id",
                "document_line_id",
                "product_id",
                "warehouse_id",
            ],
            [
                "document_lines.document_id",
                "document_lines.id",
                "document_lines.product_id",
                "document_lines.warehouse_id",
            ],
            name="fk_icve_adjustment_document_line",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_inventory_count_variance_events",
        ),
        sa.UniqueConstraint(
            "inventory_count_event_id",
            name="uq_icve_inventory_count_event",
        ),
        sa.UniqueConstraint(
            "document_line_id",
            name="uq_icve_document_line",
        ),
    )

    for column_name in (
        "company_id",
        "inventory_count_event_id",
        "document_id",
        "document_line_id",
        "product_id",
        "warehouse_id",
        "adjustment_date",
    ):
        op.create_index(
            f"ix_inventory_count_variance_events_{column_name}",
            "inventory_count_variance_events",
            [column_name],
            unique=False,
        )

    op.create_index(
        "ix_icve_stock_identity",
        "inventory_count_variance_events",
        [
            "company_id",
            "product_id",
            "warehouse_id",
            "adjustment_date",
            "id",
        ],
        unique=False,
    )


def downgrade() -> None:
    # Child tables first.

    op.drop_index(
        "ix_icve_stock_identity",
        table_name="inventory_count_variance_events",
    )

    for column_name in reversed(
        (
            "company_id",
            "inventory_count_event_id",
            "document_id",
            "document_line_id",
            "product_id",
            "warehouse_id",
            "adjustment_date",
        )
    ):
        op.drop_index(
            f"ix_inventory_count_variance_events_{column_name}",
            table_name="inventory_count_variance_events",
        )

    op.drop_table(
        "inventory_count_variance_events"
    )

    op.drop_index(
        "ix_icev_history_chain",
        table_name="inventory_count_events",
    )
    op.drop_index(
        "ix_inventory_count_events_history_key",
        table_name="inventory_count_events",
    )
    op.drop_index(
        "ix_icev_stock_identity",
        table_name="inventory_count_events",
    )

    for column_name in reversed(
        (
            "company_id",
            "product_id",
            "warehouse_id",
            "count_date",
            "reversal_of_id",
        )
    ):
        op.drop_index(
            f"ix_inventory_count_events_{column_name}",
            table_name="inventory_count_events",
        )

    op.drop_table(
        "inventory_count_events"
    )

    op.drop_index(
        "ix_wtl_product",
        table_name="warehouse_transfer_lines",
    )
    op.drop_index(
        "ix_wtl_transfer_event",
        table_name="warehouse_transfer_lines",
    )

    for column_name in reversed(
        (
            "company_id",
            "transfer_event_id",
            "product_id",
            "source_warehouse_id",
            "destination_warehouse_id",
            "issue_document_id",
            "issue_document_line_id",
            "receipt_document_id",
        )
    ):
        op.drop_index(
            f"ix_warehouse_transfer_lines_{column_name}",
            table_name="warehouse_transfer_lines",
        )

    op.drop_index(
        "ix_wtvl_source_inventory_cost_entry",
        table_name="warehouse_transfer_valuation_layers",
    )
    op.drop_index(
        "ix_wtvl_transfer_line",
        table_name="warehouse_transfer_valuation_layers",
    )

    for column_name in reversed(
        (
            "company_id",
            "transfer_line_id",
            "product_id",
            "destination_warehouse_id",
            "source_inventory_cost_entry_id",
            "source_stock_lot_consumption_id",
            "destination_receipt_document_id",
            "destination_receipt_document_line_id",
        )
    ):
        op.drop_index(
            f"ix_wtvl_{column_name}",
            table_name="warehouse_transfer_valuation_layers",
        )

    op.drop_table(
        "warehouse_transfer_valuation_layers"
    )

    op.drop_table(
        "warehouse_transfer_lines"
    )

    op.drop_index(
        "ix_wte_history_chain",
        table_name="warehouse_transfer_events",
    )
    op.drop_index(
        "ix_warehouse_transfer_events_history_key",
        table_name="warehouse_transfer_events",
    )
    op.drop_index(
        "ix_wte_company_transfer_date",
        table_name="warehouse_transfer_events",
    )

    for column_name in reversed(
        (
            "company_id",
            "source_warehouse_id",
            "destination_warehouse_id",
            "transfer_date",
            "reversal_of_id",
        )
    ):
        op.drop_index(
            f"ix_warehouse_transfer_events_{column_name}",
            table_name="warehouse_transfer_events",
        )

    op.drop_table(
        "warehouse_transfer_events"
    )
