"""add inventory valuation method to companies

Revision ID: fa75caf97ad2
Revises: 35e427fb5c59
Create Date: 2026-08-19 12:13:44.215705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa75caf97ad2'
down_revision: Union[str, Sequence[str], None] = '35e427fb5c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('inventory_valuation_method', sa.Enum('fifo', 'weighted_average_moving', 'weighted_average_periodic', 'identified_cost', 'standard_cost', 'retail_price', name='inventory_valuation_method_enum', native_enum=False), server_default='fifo', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'inventory_valuation_method')
    # ### end Alembic commands ###
